import {StyleSheet} from 'react-native';
import {
  Accessibility,
  Palette,
  Radius,
  Spacing,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../constants/designSystem';

export const walletStyles = StyleSheet.create({
  rewardsHeader: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: Spacing.md,
  },
  rewardsTitle: {...Type.title, ...textDirection, color: Palette.text},
  historyButton: {
    ...rtlRowStyle,
    gap: 6,
    minHeight: Accessibility.minTouchTarget,
    minWidth: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  historyLabel: {
    ...Type.body,
    ...textDirection,
    fontSize: 14,
    color: Palette.text,
  },
  // The existing subscription rail uses the same native horizontal-overflow
  // pattern: grow to the viewport, but never shrink system-scaled content.
  rewardsHeroViewport: {flexGrow: 0},
  rewardsHeroContent: {flexGrow: 1},
  rewardsHero: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'center',
    paddingTop: Spacing.xxs,
    paddingBottom: Spacing.md,
    gap: Spacing.md,
    flexGrow: 1,
    flexShrink: 0,
  },
  rewardsBalanceCopy: {flexShrink: 0},
  rewardsBalance: {
    ...Type.display,
    ...textDirection,
    color: Palette.text,
    fontSize: 44,
    lineHeight: 60,
    textAlign: 'center',
    flexShrink: 0,
  },
  rewardsArt: {flexShrink: 0, alignSelf: 'center'},
  disclosure: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 6,
    minHeight: Math.max(52, Accessibility.minTouchTarget),
    paddingVertical: Spacing.xs,
  },
  disclosureCopy: {
    ...rtlRowStyle,
    alignItems: 'center',
    flex: 1,
    gap: Spacing.xs,
  },
  helpDisclosure: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  rewardsSectionTitle: {
    ...Type.section,
    ...textDirection,
    color: Palette.text,
    marginTop: Spacing.md,
    marginBottom: Spacing.xs,
  },
  rewardTaskDivider: {
    borderBottomColor: Palette.lineSoft,
    borderBottomWidth: StyleSheet.hairlineWidth,
  },
  completedTask: {
    ...rtlRowStyle,
    justifyContent: 'space-between',
    gap: Spacing.sm,
    paddingVertical: Spacing.sm,
  },
  completedTaskTitle: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    flex: 1,
  },
  balanceCard: {
    paddingTop: Spacing.xxs,
    paddingBottom: Spacing.xs,
  },
  balanceRow: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: Spacing.sm,
    width: '100%',
  },
  balanceRowStacked: {
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: Spacing.sm,
  },
  balanceFullWidth: {width: '100%'},
  balanceButton: {
    alignItems: 'flex-start',
    minHeight: Accessibility.minTouchTarget,
    paddingVertical: Spacing.xxs,
  },
  balance: {
    ...Type.display,
    ...textDirection,
    color: Palette.text,
    fontSize: 44,
    lineHeight: 58,
    flexShrink: 1,
    minWidth: 0,
    maxWidth: '100%',
  },
  balanceDetails: {
    ...Type.caption,
    ...textDirection,
    color: '#8BB5FF',
    flexShrink: 1,
  },
  balanceHint: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textFaint,
    marginTop: Spacing.xs,
  },
  balanceLinks: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    gap: Spacing.md,
    marginTop: Spacing.xs,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  rulesLink: {
    minHeight: Accessibility.minTouchTarget,
    justifyContent: 'center',
    paddingVertical: Spacing.xs,
  },
  rulesLinkLabel: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    flexShrink: 1,
  },
  sectionHeading: {marginTop: Spacing.md, marginBottom: Spacing.sm},
  packages: {...rtlRowStyle, paddingBottom: Spacing.md},
  packageCard: {
    padding: Spacing.sm,
    minWidth: 0,
    borderRadius: Radius.lg,
    backgroundColor: Palette.surface,
    alignItems: 'stretch',
  },
  packageLabel: {...Type.caption, ...textDirection, color: Palette.textMuted},
  packageAmount: {marginTop: Spacing.xs, maxWidth: '100%'},
  packageCoins: {...Type.title, color: Palette.text},
  packagePrice: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xxs,
  },
  packageAction: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    gap: Spacing.xs,
    minHeight: Accessibility.minTouchTarget,
    paddingVertical: Spacing.xs,
    paddingHorizontal: Spacing.xs,
    borderRadius: Radius.sm,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.action,
    marginTop: Spacing.sm,
  },
  packageActionLabel: {
    ...Type.bodyStrong,
    ...textDirection,
    textAlign: 'center',
    color: '#FFFFFF',
    flexShrink: 1,
  },
  packageDisabled: {opacity: 0.52},
  tasksCard: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  taskRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    minHeight: 92,
    paddingVertical: Spacing.md,
  },
  taskRowStacked: {flexDirection: 'column', alignItems: 'stretch'},
  taskMain: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
    ...rtlRowStyle,
    alignItems: 'flex-start',
  },
  taskIcon: {
    width: 38,
    flexShrink: 0,
    marginEnd: Spacing.xs,
  },
  taskCopy: {flex: 1, minWidth: 0},
  taskTitleRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: Spacing.xs,
  },
  taskTitle: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    flexShrink: 1,
    flexGrow: 1,
  },
  taskDescription: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
    flexShrink: 1,
  },
  taskReward: {
    ...rtlRowStyle,
    alignItems: 'center',
    flexShrink: 0,
    gap: 2,
  },
  rewardAmount: {
    ...Type.caption,
    fontSize: 14,
    color: Palette.coin,
    writingDirection: 'ltr',
  },
  taskAction: {
    minWidth: 66,
    maxWidth: '36%',
    minHeight: Accessibility.minTouchTarget,
    paddingHorizontal: Spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.sm,
    backgroundColor: Palette.primary,
    marginStart: Spacing.sm,
    flexShrink: 0,
  },
  taskActionStacked: {
    alignSelf: 'flex-end',
    minWidth: 104,
    maxWidth: '100%',
    marginStart: 0,
    marginTop: Spacing.xs,
  },
  taskActionDone: {
    opacity: 0.52,
  },
  taskActionLabel: {
    ...Type.caption,
    fontSize: 13,
    ...textDirection,
    textAlign: 'center',
    color: Palette.text,
    flexShrink: 1,
  },
  taskActionLabelDone: {color: Palette.textFaint},
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: Palette.lineSoft,
  },
  transactionRow: {
    minHeight: 68,
    ...rtlRowStyle,
    alignItems: 'center',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.lineSoft,
  },
  transactionAmount: {
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 5,
    marginStart: Spacing.sm,
  },
  transactionCopy: {flex: 1, minWidth: 0},
  transactionTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  transactionDate: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textFaint,
  },
  transactionValue: {
    ...Type.bodyStrong,
    writingDirection: 'ltr',
    color: Palette.textMuted,
    flexShrink: 1,
  },
  positive: {color: Palette.coin},
  pressed: {opacity: 0.75},
  apiError: {
    ...Type.caption,
    ...textDirection,
    color: Palette.danger,
    flexShrink: 1,
  },
  inlineRetry: {
    minHeight: Accessibility.minTouchTarget,
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
    paddingVertical: Spacing.xs,
  },
  remoteNote: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    paddingVertical: Spacing.lg,
  },
  unavailableCard: {alignItems: 'center', marginBottom: Spacing.md},
  retryButton: {
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.lg,
    borderRadius: Radius.md,
    backgroundColor: Palette.primarySoft,
  },
  retryLabel: {...Type.caption, color: '#8BB5FF'},
  breakdownOverlay: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    backgroundColor: Palette.overlay,
  },
  breakdownSheet: {
    width: '100%',
    maxWidth: 620,
    maxHeight: '90%',
    paddingHorizontal: Spacing.xl,
    paddingTop: Spacing.md,
    borderTopLeftRadius: Radius.xl,
    borderTopRightRadius: Radius.xl,
    backgroundColor: Palette.canvasSoft,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    overflow: 'hidden',
  },
  breakdownHandle: {
    alignSelf: 'center',
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: Palette.line,
    marginBottom: Spacing.lg,
  },
  breakdownScroll: {width: '100%'},
  breakdownContent: {paddingBottom: Spacing.xs},
  sheetHeader: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
  },
  sheetClose: {
    minWidth: Accessibility.minTouchTarget,
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rulesTitle: {
    ...Type.title,
    ...textDirection,
    color: Palette.text,
    flexShrink: 1,
  },
  rulesIntro: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
    marginBottom: Spacing.md,
  },
  rulesList: {gap: Spacing.sm},
  ruleRow: {...rtlRowStyle, alignItems: 'flex-start'},
  ruleNumber: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.coinSoft,
    marginEnd: Spacing.sm,
    marginTop: 1,
  },
  ruleNumberLabel: {...Type.caption, color: '#E8C66F'},
  ruleText: {
    ...Type.body,
    ...textDirection,
    color: Palette.text,
    flex: 1,
    minWidth: 0,
  },
});
