import {StyleSheet} from 'react-native';
import {
  Palette,
  Radius,
  Spacing,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../constants/designSystem';

export const notificationStyles = StyleSheet.create({
  listContent: {paddingBottom: 100},
  headerFrame: {width: '100%', alignSelf: 'center'},
  itemFrame: {width: '100%', alignSelf: 'center'},
  footerFrame: {width: '100%', alignSelf: 'center'},
  cardPressable: {overflow: 'hidden'},
  row: {
    minHeight: 92,
    ...rtlRowStyle,
    alignItems: 'flex-start',
    gap: Spacing.sm,
    paddingVertical: Spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.lineSoft,
  },
  rowCompact: {
    minHeight: 0,
    gap: Spacing.xs,
    paddingVertical: Spacing.sm,
  },
  unreadRow: {backgroundColor: Palette.canvasSoft},
  mark: {
    width: 46,
    height: 46,
    flexShrink: 0,
    borderRadius: 14,
    backgroundColor: Palette.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  markCompact: {width: 40, height: 40, borderRadius: 12},
  coinMark: {backgroundColor: Palette.coinSoft},
  projectMark: {backgroundColor: 'rgba(72,185,138,0.12)'},
  courseMark: {backgroundColor: Palette.surface},
  courseImage: {width: '100%', height: '100%', resizeMode: 'cover'},
  markInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: Palette.primary,
  },
  copy: {flex: 1, minWidth: 0},
  titleRow: {...rtlRowStyle, alignItems: 'center'},
  title: {...Type.bodyStrong, ...textDirection, color: Palette.text, flex: 1},
  unreadDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: Palette.primary,
    marginStart: Spacing.xs,
  },
  description: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 3,
  },
  metaRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    marginTop: Spacing.sm,
  },
  metaRowCompact: {alignItems: 'flex-start', gap: Spacing.xs},
  time: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textFaint,
    flexShrink: 0,
  },
  actionPill: {
    minHeight: 30,
    maxWidth: '100%',
    justifyContent: 'center',
    flexShrink: 1,
  },
  actionLabel: {...Type.caption, ...textDirection, color: '#A8C7FF'},
  loadMore: {
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.lg,
    borderRadius: Radius.md,
  },
  loadMoreDisabled: {opacity: 0.6},
  loadMoreText: {...Type.bodyStrong, ...textDirection, color: '#A8C7FF'},
  staleNotice: {
    minHeight: 52,
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: 'rgba(240,100,105,0.2)',
    backgroundColor: 'rgba(240,100,105,0.07)',
  },
  staleNoticeText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
  },
  staleNoticeAction: {
    ...Type.caption,
    ...textDirection,
    color: Palette.danger,
    marginTop: Spacing.xxs,
  },
  pressed: {opacity: 0.66},
});
