import {StyleSheet} from 'react-native';

import {
  Palette,
  Radius,
  Spacing,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../constants/designSystem';

export const styles = StyleSheet.create({
  courseShelf: {marginTop: Spacing.md},
  courseRail: {
    ...rtlRowStyle,
    alignItems: 'stretch',
    gap: Spacing.sm,
    paddingBottom: Spacing.md,
  },
  courseCard: {
    padding: Spacing.sm,
    minWidth: 0,
    borderRadius: Radius.lg,
    backgroundColor: Palette.surface,
    alignItems: 'stretch',
  },
  courseDetails: {
    flex: 1,
    alignItems: 'stretch',
    minHeight: 48,
  },
  offlineNote: {
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
  },
  offlineNoteText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
  },
  offlineRetry: {minHeight: 48, justifyContent: 'center'},
  offlineRetryText: {...Type.caption, ...textDirection, color: Palette.primary},
  courseCover: {
    width: '100%',
    height: undefined,
    aspectRatio: 1.6,
    borderRadius: Radius.sm,
    resizeMode: 'cover',
  },
  courseCopy: {flex: 1, minWidth: 0, paddingTop: Spacing.sm},
  courseTitle: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
  },
  nextLesson: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
  },
  progressTrack: {
    height: 4,
    backgroundColor: Palette.surfacePressed,
    borderRadius: 3,
    overflow: 'hidden',
    marginTop: Spacing.xs,
  },
  progressFill: {
    height: '100%',
    backgroundColor: Palette.primary,
    borderRadius: 3,
  },
  progressLabel: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.sm,
  },
  resumeAction: {marginTop: Spacing.sm},
  resumeButton: {
    minHeight: 48,
    paddingHorizontal: Spacing.xs,
    paddingVertical: Spacing.xs,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.sm,
    backgroundColor: Palette.action,
  },
  resumeButtonPressed: {backgroundColor: Palette.actionPressed},
  resumeButtonText: {
    ...Type.bodyStrong,
    ...textDirection,
    textAlign: 'center',
    color: '#FFFFFF',
    flexShrink: 1,
  },
  section: {marginTop: Spacing.section},
  badgeGrid: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    gap: Spacing.sm,
    marginTop: Spacing.md,
  },
  badgeCard: {
    ...rtlRowStyle,
    width: '100%',
    gap: Spacing.md,
    paddingVertical: Spacing.sm,
    alignItems: 'center',
  },
  badgeCardLargeText: {alignItems: 'flex-start'},
  badgeArtwork: {width: 64, height: 64, resizeMode: 'contain'},
  badgeCopy: {flex: 1, minWidth: 0},
  badgeTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  badgeCourse: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  pathSelector: {
    ...rtlRowStyle,
    gap: Spacing.sm,
    paddingVertical: Spacing.sm,
  },
  pathChoice: {
    maxWidth: 240,
    minHeight: 48,
    justifyContent: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  pathChoiceActive: {
    borderBottomColor: Palette.primary,
  },
  pathChoiceText: {...Type.caption, ...textDirection, color: Palette.textMuted},
  pathChoiceTextActive: {color: Palette.text},
  pathCard: {marginTop: Spacing.md},
  pathProgressRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: Spacing.sm,
  },
  pathTitle: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    flexShrink: 1,
  },
  pathValue: {...Type.title, ...textDirection, color: Palette.text},
  pathHint: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.sm,
  },
  levelList: {
    marginTop: Spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  levelRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    minHeight: 72,
    paddingVertical: Spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.lineSoft,
  },
  levelRowCurrent: {backgroundColor: 'transparent'},
  levelArtwork: {width: 36, height: 36, resizeMode: 'contain'},
  levelCopy: {flex: 1, minWidth: 0, marginStart: Spacing.md},
  levelName: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  levelStatus: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  rhythmCard: {
    marginTop: Spacing.md,
    marginBottom: Spacing.xl,
  },
  streakTop: {...rtlRowStyle, alignItems: 'center', marginBottom: Spacing.lg},
  streakCopy: {flex: 1, minWidth: 0},
  streakTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  streakHint: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  weekRow: {...rtlRowStyle, justifyContent: 'space-between'},
  day: {alignItems: 'center', flex: 1},
  dayMark: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Palette.surfacePressed,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayComplete: {backgroundColor: Palette.action},
  dayMarkText: {...Type.caption, color: Palette.textFaint},
  dayMarkTextComplete: {color: Palette.text},
  dayLabel: {...Type.caption, color: Palette.textMuted, marginTop: Spacing.xs},
  rhythmText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.lg,
  },
  pressed: {opacity: 0.76},
});
