import {StyleSheet} from 'react-native';

import {
  Palette,
  Radius,
  Spacing,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../constants/designSystem';

export const styles = StyleSheet.create({
  courseGrid: {gap: Spacing.md},
  completedHeading: {marginTop: Spacing.lg},
  courseCard: {
    marginTop: Spacing.md,
    width: '100%',
    minHeight: 244,
    backgroundColor: Palette.surface,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    overflow: 'hidden',
  },
  primaryResumeCard: {
    minHeight: 284,
    borderColor: 'rgba(75,142,247,0.58)',
    borderWidth: 1.5,
  },
  offlineNote: {
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: Spacing.md,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    backgroundColor: Palette.surface,
  },
  offlineNoteText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
  },
  courseCover: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    resizeMode: 'cover',
  },
  courseCopy: {flex: 1, padding: Spacing.lg, justifyContent: 'flex-end'},
  courseTitle: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    marginTop: Spacing.sm,
    maxWidth: 520,
  },
  nextLesson: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
  },
  progressTrack: {
    height: 6,
    backgroundColor: Palette.surfacePressed,
    borderRadius: 3,
    overflow: 'hidden',
    marginTop: Spacing.md,
  },
  progressFill: {
    height: '100%',
    backgroundColor: Palette.primary,
    borderRadius: 3,
  },
  progressLabel: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textFaint,
    marginTop: Spacing.xs,
  },
  resumeButton: {
    minHeight: 48,
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.lg,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.md,
    backgroundColor: Palette.action,
  },
  resumeButtonPressed: {backgroundColor: Palette.actionPressed},
  resumeButtonText: {...Type.button, color: '#FFFFFF'},
  section: {marginTop: Spacing.xl},
  historyList: {
    marginTop: Spacing.sm,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    backgroundColor: Palette.surface,
    overflow: 'hidden',
  },
  historyRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    minHeight: 92,
    padding: Spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.lineSoft,
  },
  historyThumb: {
    width: 96,
    height: 64,
    borderRadius: Radius.md,
    backgroundColor: Palette.surfaceRaised,
  },
  historyCopy: {flex: 1, minWidth: 0, marginHorizontal: Spacing.md},
  historyTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  historyCourse: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  historyProgressTrack: {
    height: 4,
    marginTop: Spacing.sm,
    borderRadius: 2,
    overflow: 'hidden',
    backgroundColor: Palette.surfacePressed,
  },
  historyProgressFill: {
    height: '100%',
    borderRadius: 2,
    backgroundColor: Palette.primary,
  },
  historyAction: {...Type.caption, color: '#9ABFFF'},
  historySkeletonRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    padding: Spacing.md,
    gap: Spacing.md,
  },
  historySkeletonCopy: {flex: 1, gap: Spacing.sm},
  badgeGrid: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    gap: Spacing.md,
    marginTop: Spacing.sm,
  },
  badgeCard: {
    width: '47.8%',
    minHeight: 196,
    padding: Spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
  },
  badgeCardLargeText: {width: '100%'},
  badgeCardLocked: {opacity: 0.62},
  badgeArtwork: {width: 108, height: 108, resizeMode: 'contain'},
  badgeTitle: {...Type.section, color: Palette.text, marginTop: Spacing.xs},
  badgeCourse: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    textAlign: 'center',
    marginTop: 2,
  },
  badgeLockedText: {
    ...Type.caption,
    color: Palette.textFaint,
    marginTop: Spacing.xs,
  },
  pathSelector: {
    direction: 'rtl',
    gap: Spacing.sm,
    paddingVertical: Spacing.sm,
  },
  pathChoice: {
    maxWidth: 240,
    minHeight: 44,
    justifyContent: 'center',
    paddingHorizontal: Spacing.md,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: Palette.line,
    backgroundColor: Palette.surface,
  },
  pathChoiceActive: {
    borderColor: Palette.primary,
    backgroundColor: Palette.primarySoft,
  },
  pathChoiceText: {...Type.caption, ...textDirection, color: Palette.textMuted},
  pathChoiceTextActive: {color: Palette.text},
  pathCard: {padding: Spacing.lg, marginTop: Spacing.md},
  pathProgressRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  pathTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  pathValue: {...Type.bodyStrong, color: '#E9C66F'},
  pathHint: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.sm,
  },
  levelList: {
    marginTop: Spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  levelRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    minHeight: 72,
    paddingVertical: Spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.lineSoft,
  },
  levelRowCurrent: {backgroundColor: Palette.primarySoft},
  levelArtwork: {width: 48, height: 48, resizeMode: 'contain'},
  levelCopy: {flex: 1, minWidth: 0, marginStart: Spacing.md},
  levelName: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  levelStatus: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  rhythmCard: {
    padding: Spacing.lg,
    marginTop: Spacing.sm,
    marginBottom: Spacing.xl,
  },
  streakTop: {...rtlRowStyle, alignItems: 'center', marginBottom: Spacing.lg},
  streakIcon: {
    width: 58,
    height: 58,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 20,
    backgroundColor: Palette.primarySoft,
  },
  streakCopy: {flex: 1, marginStart: Spacing.md},
  streakTitle: {...Type.section, ...textDirection, color: Palette.text},
  streakHint: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  weekRow: {...rtlRowStyle, justifyContent: 'space-between'},
  day: {alignItems: 'center'},
  dayMark: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: Palette.surfacePressed,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dayComplete: {backgroundColor: Palette.action},
  dayMarkText: {...Type.caption, color: Palette.textFaint},
  dayMarkTextComplete: {color: Palette.text},
  dayLabel: {...Type.caption, color: Palette.textMuted, marginTop: Spacing.xs},
  rhythmText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.lg,
  },
  pressed: {opacity: 0.76},
});
