import {StyleSheet} from 'react-native';
import {
  Accessibility,
  Palette,
  Radius,
  Spacing,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../constants/designSystem';

export const profileStyles = StyleSheet.create({
  headerButton: {
    width: Accessibility.minTouchTarget,
    height: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileCard: {paddingTop: Spacing.sm, paddingBottom: Spacing.lg},
  staleNotice: {
    minHeight: Accessibility.minTouchTarget,
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    marginBottom: Spacing.sm,
    borderRadius: Radius.md,
    backgroundColor: 'rgba(240,100,105,0.09)',
    borderWidth: 1,
    borderColor: 'rgba(240,100,105,0.18)',
  },
  staleNoticeText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    flex: 1,
  },
  staleNoticeAction: {...Type.caption, color: '#8BB5FF', flexShrink: 0},
  profileTop: {...rtlRowStyle, alignItems: 'center', gap: Spacing.md},
  avatarButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    flexShrink: 0,
  },
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: Palette.line,
  },
  profileCopy: {flex: 1, minWidth: 0, alignItems: 'stretch'},
  name: {
    ...Type.title,
    ...textDirection,
    color: Palette.text,
  },
  role: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  availability: {marginTop: Spacing.xs},
  shareButton: {
    minHeight: Accessibility.minTouchTarget,
    flexShrink: 1,
    ...rtlRowStyle,
    gap: Spacing.xs,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: Radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.primarySoft,
  },
  shareLabel: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    flexShrink: 1,
  },
  publicActions: {
    marginTop: Spacing.md,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: Spacing.xs,
  },
  publicActionsLargeText: {flexDirection: 'column', alignItems: 'stretch'},
  publicActionButtons: {
    ...rtlRowStyle,
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: Spacing.xs,
    flexShrink: 0,
    maxWidth: '100%',
  },
  publicLink: {
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
    minHeight: Accessibility.minTouchTarget,
    justifyContent: 'center',
  },
  publicLinkLargeText: {
    width: '100%',
    flexGrow: 0,
    flexShrink: 0,
    alignSelf: 'stretch',
  },
  publicLinkText: {
    ...Type.caption,
    color: '#8BB5FF',
    direction: 'ltr',
    writingDirection: 'ltr',
    textAlign: 'left',
  },
  qrButton: {
    minWidth: Accessibility.minTouchTarget,
    minHeight: Accessibility.minTouchTarget,
    flexShrink: 0,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.sm,
    backgroundColor: Palette.surfacePressed,
  },
  qrOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.xl,
    backgroundColor: 'rgba(3, 8, 18, 0.82)',
  },
  qrCard: {
    width: '100%',
    maxWidth: 360,
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.xl,
  },
  qrTitle: {...Type.title, ...textDirection, color: Palette.text},
  qrHint: {...Type.body, ...textDirection, color: Palette.textMuted},
  qrClose: {
    minHeight: Accessibility.minTouchTarget,
    minWidth: 120,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.md,
    backgroundColor: Palette.primarySoft,
  },
  qrCloseText: {...Type.bodyStrong, color: Palette.text},
  tabs: {
    ...rtlRowStyle,
    marginBottom: Spacing.lg,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: Palette.lineSoft,
  },
  tab: {
    flex: 1,
    minHeight: Accessibility.minTouchTarget,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.xxs,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  activeTab: {borderBottomColor: Palette.primary},
  tabLabel: {
    ...Type.bodyStrong,
    ...textDirection,
    textAlign: 'center',
    color: Palette.textMuted,
  },
  activeTabLabel: {color: Palette.text, fontFamily: 'Cairo-SemiBold'},
  pressed: {opacity: 0.72},
});
