import {StyleSheet} from 'react-native';
import {
  Accessibility,
  Palette,
  Radius,
  Spacing,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../constants/designSystem';

export const profileStyles = StyleSheet.create({
  headerButton: {
    width: Accessibility.minTouchTarget,
    height: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileCard: {padding: Spacing.lg, marginBottom: Spacing.lg},
  staleNotice: {
    minHeight: Accessibility.minTouchTarget,
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    marginBottom: Spacing.sm,
    borderRadius: Radius.md,
    backgroundColor: 'rgba(240,100,105,0.09)',
    borderWidth: 1,
    borderColor: 'rgba(240,100,105,0.18)',
  },
  staleNoticeText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    flex: 1,
  },
  staleNoticeAction: {...Type.caption, color: '#8BB5FF', flexShrink: 0},
  profileTop: {...rtlRowStyle, alignItems: 'center'},
  avatar: {
    width: 72,
    height: 72,
    borderRadius: 36,
    borderWidth: 2,
    borderColor: Palette.line,
  },
  profileCopy: {flex: 1, marginHorizontal: Spacing.md},
  name: {...Type.title, ...textDirection, color: Palette.text},
  role: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  availability: {marginTop: Spacing.xs},
  shareButton: {
    width: Accessibility.minTouchTarget,
    height: Accessibility.minTouchTarget,
    borderRadius: Radius.md,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.primarySoft,
    borderWidth: 1,
    borderColor: 'rgba(52,120,246,0.24)',
  },
  publicActions: {
    marginTop: Spacing.md,
    paddingTop: Spacing.md,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: Spacing.sm,
  },
  publicLink: {
    flex: 1,
    minHeight: Accessibility.minTouchTarget,
    justifyContent: 'center',
  },
  publicLinkText: {
    ...Type.bodyStrong,
    color: '#8BB5FF',
    writingDirection: 'ltr',
    textAlign: 'left',
  },
  qrButton: {
    minWidth: Accessibility.minTouchTarget,
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.sm,
    backgroundColor: Palette.surfacePressed,
  },
  qrButtonText: {...Type.bodyStrong, color: Palette.text},
  qrOverlay: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.xl,
    backgroundColor: 'rgba(3, 8, 18, 0.82)',
  },
  qrCard: {
    width: '100%',
    maxWidth: 360,
    alignItems: 'center',
    gap: Spacing.md,
    padding: Spacing.xl,
  },
  qrTitle: {...Type.title, ...textDirection, color: Palette.text},
  qrHint: {...Type.body, ...textDirection, color: Palette.textMuted},
  qrClose: {
    minHeight: Accessibility.minTouchTarget,
    minWidth: 120,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.md,
    backgroundColor: Palette.primarySoft,
  },
  qrCloseText: {...Type.bodyStrong, color: Palette.text},
  tabs: {
    ...rtlRowStyle,
    backgroundColor: Palette.surface,
    borderRadius: Radius.md,
    padding: 4,
    marginBottom: Spacing.lg,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  tab: {
    flex: 1,
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.sm,
  },
  activeTab: {backgroundColor: Palette.surfacePressed},
  tabLabel: {...Type.caption, color: Palette.textMuted},
  activeTabLabel: {color: Palette.text, fontFamily: 'Cairo-SemiBold'},
  pressed: {opacity: 0.72},
});
