import {StyleSheet} from 'react-native';

import {
  Accessibility,
  Palette,
  Radius,
  Spacing,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../constants/designSystem';

export const styles = StyleSheet.create({
  frame: {maxWidth: 760, paddingBottom: Spacing.section},
  modeTabs: {
    ...rtlRowStyle,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.line,
    marginBottom: Spacing.lg,
  },
  modeButton: {
    flex: 1,
    minHeight: Accessibility.minTouchTarget,
    paddingHorizontal: Spacing.xs,
    paddingVertical: Spacing.sm,
    alignItems: 'center',
    justifyContent: 'center',
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  modeButtonSelected: {borderBottomColor: Palette.primary},
  modeButtonText: {
    ...Type.bodyStrong,
    ...textDirection,
    textAlign: 'center',
    color: Palette.text,
  },
  casesCard: {marginTop: Spacing.sm},
  casesHeader: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: Spacing.sm,
    paddingBottom: Spacing.sm,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.line,
  },
  casesHeadingCopy: {flexGrow: 1, flexShrink: 1, minWidth: 120},
  caseHeading: {...Type.section, ...textDirection, color: Palette.text},
  caseHeaderAction: {
    minHeight: Accessibility.minTouchTarget,
    minWidth: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  refreshCases: {
    ...Type.caption,
    color: '#9ABFFF',
  },
  caseMuted: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.sm,
  },
  caseRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    minHeight: 88,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.line,
    paddingVertical: Spacing.md,
    gap: Spacing.sm,
  },
  caseRowSelected: {backgroundColor: Palette.primarySoft},
  caseCopy: {flex: 1, minWidth: 0},
  caseSubject: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  caseNumber: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xxs,
  },
  caseStatus: {
    ...Type.caption,
    ...textDirection,
    color: '#9ABFFF',
    maxWidth: 120,
    flexShrink: 1,
  },
  timeline: {marginTop: Spacing.lg},
  timelineMessage: {
    alignSelf: 'flex-start',
    maxWidth: '94%',
    borderRadius: Radius.md,
    backgroundColor: Palette.surface,
    padding: Spacing.md,
    marginBottom: Spacing.md,
  },
  timelineSupport: {
    alignSelf: 'flex-end',
    backgroundColor: Palette.primarySoft,
  },
  timelineAuthor: {...Type.caption, ...textDirection, color: Palette.textMuted},
  timelineText: {
    ...Type.body,
    ...textDirection,
    color: Palette.text,
    marginTop: Spacing.xxs,
  },
  timelineAttachment: {
    alignSelf: 'flex-start',
    marginTop: Spacing.sm,
  },
  timelineAttachmentImage: {
    width: 112,
    height: 84,
    borderRadius: Radius.md,
    backgroundColor: Palette.canvasSoft,
  },
  timelineAttachmentLabel: {
    ...Type.caption,
    color: '#9ABFFF',
    marginTop: Spacing.xxs,
  },
  replyInput: {
    ...Type.body,
    ...textDirection,
    color: Palette.text,
    minHeight: 100,
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: Radius.md,
    backgroundColor: Palette.surface,
    padding: Spacing.md,
    marginTop: Spacing.sm,
  },
  replyButton: {
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.md,
    backgroundColor: Palette.primary,
    marginTop: Spacing.sm,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
  },
  replyAttachmentButton: {
    minHeight: Accessibility.minTouchTarget,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    marginTop: Spacing.xs,
  },
  heading: {marginTop: Spacing.sm},
  replyLabel: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    marginTop: Spacing.lg,
  },
  categoryLabel: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    marginTop: Spacing.xl,
  },
  intro: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
  },
  categories: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    gap: Spacing.xs,
    marginTop: Spacing.sm,
  },
  category: {
    maxWidth: '100%',
    minHeight: Accessibility.minTouchTarget,
    justifyContent: 'center',
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.xs,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: Palette.line,
    backgroundColor: Palette.surface,
  },
  categorySelected: {
    borderColor: Palette.primary,
    backgroundColor: Palette.primarySoft,
  },
  categoryText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    flexShrink: 1,
  },
  categoryTextSelected: {color: '#9ABFFF'},
  form: {marginTop: Spacing.xl},
  label: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  input: {
    ...Type.body,
    ...textDirection,
    color: Palette.text,
    minHeight: 164,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Palette.line,
    backgroundColor: Palette.surface,
    padding: Spacing.md,
    marginTop: Spacing.sm,
  },
  counter: {
    ...Type.caption,
    color: Palette.textFaint,
    marginTop: Spacing.xs,
    direction: 'ltr',
    writingDirection: 'ltr',
    textAlign: 'left',
  },
  attachmentButton: {
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'flex-start',
    justifyContent: 'center',
    borderRadius: Radius.md,
    marginTop: Spacing.md,
    paddingHorizontal: 0,
    paddingVertical: Spacing.sm,
  },
  attachmentButtonText: {...Type.bodyStrong, color: '#9ABFFF'},
  attachmentRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    gap: Spacing.md,
    marginTop: Spacing.md,
  },
  attachmentImage: {
    width: 74,
    height: 74,
    borderRadius: Radius.md,
    resizeMode: 'cover',
  },
  attachmentCopy: {flex: 1, minWidth: 0},
  removeAttachmentButton: {
    minHeight: Accessibility.minTouchTarget,
    minWidth: Accessibility.minTouchTarget,
    justifyContent: 'center',
    alignSelf: 'flex-start',
  },
  attachmentTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  removeAttachment: {
    ...Type.caption,
    color: Palette.danger,
    marginTop: Spacing.xxs,
  },
  diagnosticsRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    minHeight: Accessibility.minTouchTarget,
    marginTop: Spacing.md,
    gap: Spacing.sm,
    paddingTop: Spacing.lg,
    paddingBottom: Spacing.sm,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  diagnosticsCheck: {
    width: 22,
    height: 22,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 6,
    borderWidth: 1,
    borderColor: Palette.line,
  },
  diagnosticsCheckSelected: {
    borderColor: Palette.primary,
    backgroundColor: Palette.primary,
  },
  diagnosticsCopy: {flex: 1, minWidth: 0},
  diagnosticsTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  diagnosticsHint: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xxs,
  },
  error: {
    ...Type.caption,
    ...textDirection,
    color: Palette.danger,
    marginTop: Spacing.md,
  },
  submit: {
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.md,
    backgroundColor: Palette.primary,
    marginTop: Spacing.lg,
    paddingVertical: Spacing.sm,
    paddingHorizontal: Spacing.md,
  },
  submitDisabled: {opacity: 0.45},
  submitText: {...Type.button, color: Palette.text},
  pressed: {opacity: 0.75},
  receipt: {
    ...Type.caption,
    color: Palette.textMuted,
    textAlign: 'center',
    marginTop: Spacing.sm,
  },
  previewBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.94)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.md,
  },
  previewClose: {
    position: 'absolute',
    top: Spacing.xl,
    end: Spacing.lg,
    minWidth: Accessibility.minTouchTarget,
    minHeight: Accessibility.minTouchTarget,
    justifyContent: 'center',
    zIndex: 2,
  },
  previewCloseText: {...Type.bodyStrong, color: '#FFFFFF'},
  previewImage: {width: '100%', height: '82%'},
  previewRetry: {
    minHeight: Accessibility.minTouchTarget,
    justifyContent: 'center',
    paddingHorizontal: Spacing.lg,
  },
  previewRetryText: {...Type.bodyStrong, color: '#FFFFFF'},
});
