import {StyleSheet} from 'react-native';

import {
  Accessibility,
  Palette,
  Radius,
  Spacing,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../constants/designSystem';

export const styles = StyleSheet.create({
  frame: {paddingBottom: Spacing.section},
  casesCard: {padding: Spacing.lg, marginTop: Spacing.md},
  casesHeader: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  refreshCases: {
    ...Type.caption,
    color: '#9ABFFF',
    paddingVertical: Spacing.sm,
  },
  caseMuted: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.sm,
  },
  caseRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    minHeight: Accessibility.minTouchTarget,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.line,
    paddingVertical: Spacing.sm,
    gap: Spacing.sm,
  },
  caseRowSelected: {backgroundColor: Palette.primarySoft},
  caseCopy: {flex: 1, alignItems: 'flex-start'},
  caseNumber: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  caseMessage: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xxs,
  },
  caseStatus: {...Type.caption, color: '#9ABFFF'},
  timeline: {marginTop: Spacing.lg},
  timelineMessage: {
    alignSelf: 'stretch',
    borderRadius: Radius.md,
    backgroundColor: Palette.canvasSoft,
    padding: Spacing.md,
    marginBottom: Spacing.sm,
  },
  timelineSupport: {backgroundColor: Palette.primarySoft},
  timelineAuthor: {...Type.caption, ...textDirection, color: Palette.textMuted},
  timelineText: {
    ...Type.body,
    ...textDirection,
    color: Palette.text,
    marginTop: Spacing.xxs,
  },
  timelineAttachment: {
    alignSelf: 'flex-start',
    marginTop: Spacing.sm,
  },
  timelineAttachmentImage: {
    width: 112,
    height: 84,
    borderRadius: Radius.md,
    backgroundColor: Palette.canvasSoft,
  },
  timelineAttachmentLabel: {
    ...Type.caption,
    color: '#9ABFFF',
    marginTop: Spacing.xxs,
  },
  replyInput: {
    ...Type.body,
    ...textDirection,
    color: Palette.text,
    minHeight: 100,
    borderWidth: 1,
    borderColor: Palette.line,
    borderRadius: Radius.md,
    padding: Spacing.md,
    marginTop: Spacing.sm,
  },
  replyButton: {
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.md,
    backgroundColor: Palette.primary,
    marginTop: Spacing.sm,
  },
  replyAttachmentButton: {
    minHeight: Accessibility.minTouchTarget,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    marginTop: Spacing.xs,
  },
  heading: {marginTop: Spacing.sm},
  intro: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
  },
  categories: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    gap: Spacing.xs,
    marginTop: Spacing.lg,
  },
  category: {
    minHeight: Accessibility.minTouchTarget,
    justifyContent: 'center',
    paddingHorizontal: Spacing.md,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: Palette.line,
    backgroundColor: Palette.surface,
  },
  categorySelected: {
    borderColor: Palette.primary,
    backgroundColor: Palette.primarySoft,
  },
  categoryText: {...Type.caption, color: Palette.textMuted},
  categoryTextSelected: {color: '#9ABFFF'},
  form: {padding: Spacing.lg, marginTop: Spacing.md},
  label: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  input: {
    ...Type.body,
    ...textDirection,
    color: Palette.text,
    minHeight: 164,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Palette.line,
    backgroundColor: Palette.canvasSoft,
    padding: Spacing.md,
    marginTop: Spacing.sm,
  },
  counter: {
    ...Type.caption,
    color: Palette.textFaint,
    marginTop: Spacing.xs,
    direction: 'ltr',
    writingDirection: 'ltr',
    textAlign: 'left',
  },
  attachmentButton: {
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.md,
    backgroundColor: Palette.primarySoft,
    marginTop: Spacing.md,
    paddingHorizontal: Spacing.md,
  },
  attachmentButtonText: {...Type.bodyStrong, color: '#9ABFFF'},
  attachmentRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    gap: Spacing.md,
    marginTop: Spacing.md,
  },
  attachmentImage: {
    width: 74,
    height: 74,
    borderRadius: Radius.md,
    resizeMode: 'cover',
  },
  attachmentCopy: {flex: 1, alignItems: 'flex-start'},
  attachmentTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  removeAttachment: {
    ...Type.caption,
    color: Palette.danger,
    marginTop: Spacing.xxs,
  },
  diagnosticsRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    minHeight: Accessibility.minTouchTarget,
    marginTop: Spacing.md,
    gap: Spacing.sm,
  },
  diagnosticsCheck: {
    width: 22,
    height: 22,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.sm,
    borderWidth: 1,
    borderColor: Palette.line,
  },
  diagnosticsCheckSelected: {
    borderColor: Palette.primary,
    backgroundColor: Palette.primary,
  },
  diagnosticsCheckMark: {...Type.caption, color: Palette.text},
  diagnosticsCopy: {flex: 1, alignItems: 'flex-start'},
  diagnosticsTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  diagnosticsHint: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xxs,
  },
  error: {
    ...Type.caption,
    ...textDirection,
    color: Palette.danger,
    marginTop: Spacing.md,
  },
  submit: {
    minHeight: 56,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.md,
    backgroundColor: Palette.primary,
    marginTop: Spacing.lg,
  },
  submitDisabled: {opacity: 0.45},
  submitText: {...Type.button, color: Palette.text},
  pressed: {opacity: 0.75},
  receipt: {
    ...Type.caption,
    color: Palette.textMuted,
    textAlign: 'center',
    marginTop: Spacing.sm,
  },
  previewBackdrop: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.94)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.md,
  },
  previewClose: {
    position: 'absolute',
    top: Spacing.xl,
    right: Spacing.lg,
    minHeight: Accessibility.minTouchTarget,
    justifyContent: 'center',
    zIndex: 2,
  },
  previewCloseText: {...Type.bodyStrong, color: '#FFFFFF'},
  previewImage: {width: '100%', height: '82%'},
  previewRetry: {
    minHeight: Accessibility.minTouchTarget,
    justifyContent: 'center',
    paddingHorizontal: Spacing.lg,
  },
  previewRetryText: {...Type.bodyStrong, color: '#FFFFFF'},
});
