import {StyleSheet} from 'react-native';
import {
  Palette,
  Radius,
  Spacing,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../../constants/designSystem';

export const certificateStyles = StyleSheet.create({
  container: {paddingBottom: Spacing.xl},
  grid: {
    direction: 'rtl',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.md,
  },
  card: {
    flexBasis: 320,
    flexGrow: 1,
    maxWidth: 620,
    marginTop: Spacing.md,
    alignSelf: 'flex-start',
    borderRadius: Radius.lg,
    overflow: 'hidden',
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  cardNarrow: {flexBasis: '100%', maxWidth: '100%'},
  lockedSection: {marginTop: Spacing.xl},
  partialNotice: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginBottom: Spacing.sm,
  },
  pendingNotice: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  pendingAction: {...Type.caption, color: Palette.primary},
  lockedHeading: {...Type.section, ...textDirection, color: Palette.text},
  lockedIntro: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
    marginBottom: Spacing.sm,
  },
  lockedCard: {
    ...rtlRowStyle,
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: 'rgba(216,166,60,.22)',
    backgroundColor: Palette.coinSoft,
  },
  readyCard: {
    borderColor: 'rgba(72,185,138,.24)',
    backgroundColor: 'rgba(72,185,138,.1)',
  },
  lockedIcon: {
    width: 44,
    height: 44,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(216,166,60,.14)',
  },
  lockedIconText: {fontSize: 24, color: '#E5BD67'},
  readyIcon: {backgroundColor: 'rgba(72,185,138,.14)'},
  lockedCopy: {flex: 1},
  lockedTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  lockedMeta: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  lockedAction: {...Type.caption, color: '#E5BD67'},
  readyAction: {...Type.caption, color: Palette.success},
  cardCopy: {padding: Spacing.md},
  title: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    marginTop: Spacing.sm,
  },
  verifiedRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    marginTop: Spacing.xs,
  },
  verifiedDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Palette.success,
    marginEnd: Spacing.xs,
  },
  verified: {...Type.caption, color: Palette.success},
  artifactPreview: {
    width: '100%',
    aspectRatio: 4 / 3,
    overflow: 'hidden',
    backgroundColor: '#F7F4ED',
  },
  artifactImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    backgroundColor: '#F7F4ED',
  },
  artifactImageLoading: {opacity: 0},
  artifactState: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.lg,
  },
  artifactStateText: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
  },
  overlay: {
    flex: 1,
    backgroundColor: Palette.overlay,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  sheet: {
    width: '100%',
    maxWidth: 760,
    maxHeight: '94%',
    backgroundColor: Palette.canvasSoft,
    borderTopLeftRadius: Radius.xl,
    borderTopRightRadius: Radius.xl,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    overflow: 'hidden',
  },
  issueSheet: {maxWidth: 560},
  sheetContent: {paddingBottom: Spacing.xl},
  detailCopy: {padding: Spacing.xl},
  detailTitle: {
    ...Type.title,
    ...textDirection,
    color: Palette.text,
    marginTop: Spacing.sm,
  },
  detailMeta: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
  },
  issueHint: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
  },
  issueInput: {
    ...Type.body,
    ...textDirection,
    minHeight: 52,
    color: Palette.text,
    backgroundColor: Palette.surface,
    borderColor: Palette.line,
    borderWidth: 1,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    marginTop: Spacing.lg,
    marginBottom: Spacing.sm,
  },
  badge: {marginTop: Spacing.md},
  qrDestination: {
    marginTop: Spacing.lg,
    padding: Spacing.md,
    borderRadius: Radius.md,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: Spacing.md,
  },
  qrCopy: {flex: 1},
  qrTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  qrLink: {
    ...Type.caption,
    color: '#8BB5FF',
    marginTop: Spacing.xs,
    direction: 'ltr',
    writingDirection: 'ltr',
    textAlign: 'left',
  },
  qrHint: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
  },
  pressed: {opacity: 0.8, transform: [{scale: 0.99}]},
});
