import {StyleSheet} from 'react-native';
import {
  Accessibility,
  Palette,
  Radius,
  Spacing,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../../constants/designSystem';

export const certificateStyles = StyleSheet.create({
  container: {paddingBottom: Spacing.xl},
  grid: {
    direction: 'rtl',
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: Spacing.md,
  },
  card: {
    ...rtlRowStyle,
    alignItems: 'center',
    gap: Spacing.md,
    flexBasis: 320,
    flexGrow: 1,
    maxWidth: 620,
    paddingVertical: Spacing.md,
    alignSelf: 'flex-start',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: Palette.lineSoft,
  },
  cardNarrow: {flexBasis: '100%', maxWidth: '100%'},
  cardLargeText: {flexDirection: 'column', alignItems: 'stretch'},
  artifactThumb: {width: 108, borderRadius: Radius.sm, overflow: 'hidden'},
  artifactThumbLargeText: {width: '100%', maxWidth: 320},
  lockedSection: {marginTop: Spacing.xl},
  partialNotice: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginBottom: Spacing.sm,
  },
  pendingNotice: {
    minHeight: 48,
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
  },
  pendingAction: {...Type.caption, color: Palette.primary},
  lockedHeading: {...Type.section, ...textDirection, color: Palette.text},
  lockedIntro: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
    marginBottom: Spacing.sm,
  },
  lockedCard: {
    ...rtlRowStyle,
    alignItems: 'center',
    gap: Spacing.sm,
    marginTop: Spacing.sm,
    minHeight: 80,
    paddingVertical: Spacing.md,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: Palette.lineSoft,
  },
  readyCard: {borderColor: Palette.lineSoft},
  lockedIcon: {
    width: 44,
    height: 44,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
  },
  lockedCopy: {flex: 1, minWidth: 0},
  lockedTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  lockedMeta: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  lockedAction: {
    ...Type.caption,
    ...textDirection,
    maxWidth: '28%',
    color: Palette.primary,
  },
  readyAction: {...Type.caption, ...textDirection, color: Palette.primary},
  cardCopy: {flex: 1, minWidth: 0},
  title: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    marginTop: Spacing.sm,
  },
  verifiedRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    marginTop: Spacing.xs,
  },
  verifiedDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: Palette.success,
    marginEnd: Spacing.xs,
  },
  verified: {
    ...Type.caption,
    ...textDirection,
    flexShrink: 1,
    color: Palette.textMuted,
  },
  artifactPreview: {
    width: '100%',
    aspectRatio: 28 / 19,
    overflow: 'hidden',
    backgroundColor: '#fcfcfa',
  },
  artifactImage: {
    ...StyleSheet.absoluteFillObject,
    width: '100%',
    height: '100%',
    backgroundColor: '#fcfcfa',
  },
  artifactImageLoading: {opacity: 0},
  artifactState: {
    ...StyleSheet.absoluteFillObject,
    alignItems: 'center',
    justifyContent: 'center',
    padding: Spacing.lg,
  },
  artifactStateText: {
    ...Type.body,
    ...textDirection,
    color: '#46566B',
  },
  artifactStateCompact: {padding: Spacing.xs},
  artifactStateTextCompact: {...Type.caption, textAlign: 'center'},
  overlay: {
    flex: 1,
    backgroundColor: Palette.overlay,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  sheet: {
    width: '100%',
    maxWidth: 760,
    maxHeight: '94%',
    backgroundColor: Palette.canvasSoft,
    borderTopLeftRadius: Radius.xl,
    borderTopRightRadius: Radius.xl,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    overflow: 'hidden',
  },
  issueSheet: {maxWidth: 560},
  sheetContent: {paddingBottom: Spacing.xl},
  detailHeader: {
    alignItems: 'flex-end',
    paddingVertical: Spacing.xxs,
  },
  closeDetail: {
    minWidth: Accessibility.minTouchTarget,
    minHeight: Accessibility.minTouchTarget,
    paddingHorizontal: Spacing.sm,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: Radius.sm,
  },
  closeDetailText: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.textMuted,
  },
  detailCopy: {padding: Spacing.xl},
  detailTitle: {
    ...Type.title,
    ...textDirection,
    color: Palette.text,
    marginTop: Spacing.sm,
  },
  detailMeta: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
  },
  issueHint: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
  },
  issueInput: {
    ...Type.body,
    ...textDirection,
    minHeight: 52,
    color: Palette.text,
    backgroundColor: Palette.surface,
    borderColor: Palette.line,
    borderWidth: 1,
    borderRadius: Radius.md,
    paddingHorizontal: Spacing.md,
    marginTop: Spacing.lg,
    marginBottom: Spacing.sm,
  },
  qrDestination: {
    marginTop: Spacing.lg,
    paddingVertical: Spacing.md,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: Spacing.md,
  },
  qrCopy: {flexShrink: 1, minWidth: 0},
  qrDestinationLargeText: {flexDirection: 'column', alignItems: 'flex-start'},
  qrTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  detailActions: {marginTop: Spacing.lg, gap: Spacing.sm},
  shareAction: {
    minHeight: Accessibility.minTouchTarget,
    paddingHorizontal: Spacing.md,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.md,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Palette.primary,
  },
  shareActionPressed: {backgroundColor: Palette.primaryPressed},
  shareActionText: {
    ...Type.button,
    ...textDirection,
    textAlign: 'center',
    color: Palette.text,
  },
  secondaryActions: {...rtlRowStyle, flexWrap: 'wrap', gap: Spacing.sm},
  secondaryActionsLargeText: {flexDirection: 'column', alignItems: 'stretch'},
  secondaryAction: {
    flexGrow: 1,
    flexBasis: 128,
    minWidth: 0,
    minHeight: Accessibility.minTouchTarget,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.sm,
    borderRadius: Radius.sm,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Palette.surface,
  },
  secondaryActionLargeText: {flexBasis: 'auto', width: '100%'},
  secondaryActionText: {
    ...Type.bodyStrong,
    ...textDirection,
    textAlign: 'center',
    color: Palette.text,
  },
  detailActionPressed: {backgroundColor: Palette.surfacePressed},
  pressed: {opacity: 0.8, transform: [{scale: 0.99}]},
});
