import {Platform, StyleSheet} from 'react-native';
import {Palette, rtlRowStyle, textDirection} from '../../../constants/designSystem';
import {Fonts} from '../../../constants/styleConstants';

export const courseChatStyles = StyleSheet.create({
  modal: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,.34)',
  },
  sheet: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    backgroundColor: '#0D121A',
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    borderWidth: 1,
    borderBottomWidth: 0,
    borderColor: 'rgba(255,255,255,.1)',
    overflow: 'hidden',
  },
  handle: {
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,.26)',
    alignSelf: 'center',
    marginTop: 9,
  },
  header: {
    minHeight: 72,
    paddingHorizontal: 16,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,.08)',
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  title: {
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.bold,
    fontSize: 16,
  },
  presenceRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 5,
    marginTop: 2,
  },
  presenceDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,.32)',
  },
  presenceDotConnected: {
    backgroundColor: Palette.success,
  },
  presenceDotWorking: {
    backgroundColor: Palette.coin,
  },
  presenceText: {
    color: 'rgba(255,255,255,.62)',
    fontFamily: Fonts.medium,
    fontSize: 10,
  },
  closeButton: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,.06)',
  },
  closeText: {
    color: '#FFFFFF',
    fontSize: 25,
    lineHeight: 27,
    fontFamily: Fonts.light,
  },
  messages: {
    flex: 1,
  },
  messagesContent: {
    paddingHorizontal: 14,
    paddingVertical: 18,
    gap: 10,
  },
  bubble: {
    maxWidth: '86%',
    minHeight: 42,
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 17,
    justifyContent: 'center',
  },
  userBubble: {
    alignSelf: 'flex-end',
    backgroundColor: '#236FE8',
    borderBottomRightRadius: 5,
  },
  assistantBubble: {
    alignSelf: 'flex-start',
    backgroundColor: '#192230',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,.07)',
    borderBottomLeftRadius: 5,
  },
  bubbleText: {
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.regular,
    fontSize: 14,
    lineHeight: 22,
  },
  retryText: {
    color: '#9FC0FF',
    fontFamily: Fonts.bold,
    fontSize: 12,
    marginTop: 8,
  },
  copyText: {
    color: 'rgba(255,255,255,.58)',
    fontFamily: Fonts.medium,
    fontSize: 11,
    marginTop: 7,
    width: 34,
    textAlign: 'center',
  },
  messageAttachment: {
    color: 'rgba(255,255,255,.78)',
    fontFamily: Fonts.medium,
    fontSize: 11,
    marginTop: 5,
  },
  workingIndicator: {
    minWidth: 42,
    minHeight: 20,
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  workingDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,.86)',
  },
  entitlementGate: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingBottom: 30,
  },
  entitlementTitle: {
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.bold,
    fontSize: 22,
    lineHeight: 32,
  },
  entitlementText: {
    ...textDirection,
    color: 'rgba(255,255,255,.72)',
    fontFamily: Fonts.regular,
    fontSize: 15,
    lineHeight: 26,
    marginTop: 12,
  },
  entitlementButton: {
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: Palette.primary,
    marginTop: 24,
  },
  entitlementButtonPressed: {
    opacity: 0.82,
  },
  entitlementButtonDisabled: {
    opacity: 0.62,
  },
  entitlementButtonText: {
    color: '#FFFFFF',
    fontFamily: Fonts.bold,
    fontSize: 16,
  },
  upgradeCard: {
    marginTop: 20,
    padding: 14,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,.1)',
    backgroundColor: 'rgba(255,255,255,.055)',
  },
  upgradeRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  upgradeLabel: {
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.semiBold,
    fontSize: 14,
  },
  upgradeValue: {
    color: '#E9C86D',
    fontFamily: Fonts.bold,
    fontSize: 14,
  },
  upgradeDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(255,255,255,.09)',
    marginVertical: 11,
  },
  upgradeHint: {
    ...textDirection,
    color: 'rgba(255,255,255,.62)',
    fontFamily: Fonts.regular,
    fontSize: 12,
  },
  upgradeHintValue: {
    color: 'rgba(255,255,255,.82)',
    fontFamily: Fonts.semiBold,
    fontSize: 12,
  },
  upgradeDeficit: {
    ...textDirection,
    color: '#FFB1B1',
    fontFamily: Fonts.medium,
    fontSize: 12,
    marginTop: 10,
  },
  upgradeError: {
    ...textDirection,
    color: '#FFB1B1',
    fontFamily: Fonts.regular,
    fontSize: 12,
    lineHeight: 20,
    marginTop: 12,
  },
  composer: {
    minHeight: 72,
    padding: 10,
    paddingBottom: Platform.OS === 'ios' ? 18 : 10,
    ...rtlRowStyle,
    alignItems: 'flex-end',
    gap: 8,
    borderTopWidth: 1,
    borderTopColor: 'rgba(255,255,255,.08)',
    backgroundColor: '#0B1017',
  },
  attachmentStrip: {
    flexGrow: 0,
    maxHeight: 58,
    paddingHorizontal: 10,
    paddingTop: 8,
    backgroundColor: '#0B1017',
  },
  stopButton: {
    alignSelf: 'center',
    marginVertical: 6,
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 14,
    backgroundColor: '#192230',
  },
  stopButtonText: {color: '#FFFFFF', fontFamily: Fonts.medium, fontSize: 12},
  attachmentChip: {
    height: 44,
    maxWidth: 190,
    marginEnd: 8,
    paddingHorizontal: 8,
    borderRadius: 12,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 7,
    backgroundColor: '#192230',
  },
  attachmentPreview: {width: 30, height: 30, borderRadius: 7},
  attachmentName: {
    maxWidth: 110,
    color: '#FFFFFF',
    fontFamily: Fonts.regular,
    fontSize: 12,
  },
  attachmentRemove: {color: '#FFFFFF', fontSize: 20, lineHeight: 22},
  attachButton: {
    width: 42,
    height: 48,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#192230',
  },
  attachButtonText: {color: '#FFFFFF', fontSize: 24, lineHeight: 26},
  input: {
    ...textDirection,
    flex: 1,
    minHeight: 48,
    maxHeight: 110,
    borderRadius: 18,
    paddingHorizontal: 14,
    paddingVertical: 11,
    color: '#FFFFFF',
    backgroundColor: '#161E29',
    fontFamily: Fonts.regular,
    fontSize: 14,
    lineHeight: 21,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 17,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#236FE8',
  },
  sendButtonDisabled: {
    opacity: 0.38,
  },
});
