import {Platform, StyleSheet} from 'react-native';
import {
  Palette,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../../constants/designSystem';
import {Fonts} from '../../../constants/styleConstants';

export const courseChatStyles = StyleSheet.create({
  modal: {
    flex: 1,
    justifyContent: 'flex-end',
  },
  backdrop: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,.34)',
  },
  sheet: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    backgroundColor: Palette.canvas,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    overflow: 'hidden',
  },
  handle: {
    width: 42,
    height: 4,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,.26)',
    alignSelf: 'center',
    marginTop: 9,
  },
  header: {
    minHeight: 72,
    paddingHorizontal: 16,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.lineSoft,
  },
  headerCopy: {
    flex: 1,
    minWidth: 0,
  },
  compactHeader: {
    minHeight: 56,
  },
  title: {
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.bold,
    fontSize: 16,
  },
  presenceRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    alignSelf: 'flex-start',
    gap: 5,
    marginTop: 2,
  },
  presenceDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,.32)',
  },
  presenceDotConnected: {
    backgroundColor: Palette.success,
  },
  presenceDotWorking: {
    backgroundColor: Palette.textMuted,
  },
  presenceText: {
    ...textDirection,
    color: Palette.textMuted,
    fontFamily: Fonts.medium,
    fontSize: 12,
  },
  closeButton: {
    width: 48,
    height: 48,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.surface,
  },
  closeText: {
    color: '#FFFFFF',
    fontSize: 25,
    lineHeight: 27,
    fontFamily: Fonts.light,
  },
  messages: {
    flex: 1,
    minHeight: 0,
  },
  messagesContent: {
    direction: 'rtl',
    paddingHorizontal: 18,
    paddingVertical: 24,
    gap: 24,
  },
  bubble: {
    maxWidth: '100%',
    minHeight: 42,
    paddingHorizontal: 14,
    paddingVertical: 14,
    borderRadius: 17,
    justifyContent: 'center',
  },
  userBubble: {
    alignSelf: 'flex-start',
    maxWidth: '90%',
    backgroundColor: Palette.surfaceRaised,
    borderBottomStartRadius: 5,
  },
  assistantBubble: {
    alignSelf: 'stretch',
    paddingHorizontal: 0,
    paddingVertical: 2,
    backgroundColor: 'transparent',
  },
  senderLabel: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginBottom: 8,
  },
  bubbleText: {
    ...textDirection,
    ...Type.body,
    color: Palette.text,
    lineHeight: 27,
  },
  retryAction: {
    minWidth: 48,
    minHeight: 48,
    alignSelf: 'flex-start',
    justifyContent: 'center',
    paddingVertical: 8,
  },
  retryText: {
    ...textDirection,
    color: Palette.text,
    fontFamily: Fonts.bold,
    fontSize: 12,
  },
  messageAttachmentAction: {
    minHeight: 48,
    justifyContent: 'center',
    paddingVertical: 10,
    marginTop: 8,
    paddingHorizontal: 12,
    borderRadius: 12,
    backgroundColor: Palette.surface,
  },
  messageAttachment: {
    ...Type.caption,
    ...textDirection,
    color: Palette.text,
  },
  workingIndicator: {
    minWidth: 42,
    minHeight: 20,
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 5,
  },
  workingDot: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: 'rgba(255,255,255,.86)',
  },
  entitlementGate: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingHorizontal: 24,
    paddingBottom: 30,
    paddingTop: 24,
  },
  entitlementTitle: {
    ...Type.title,
    ...textDirection,
    color: '#FFFFFF',
  },
  entitlementText: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 12,
  },
  entitlementButton: {
    minHeight: 52,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 15,
    backgroundColor: Palette.primary,
    marginTop: 24,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  entitlementButtonPressed: {
    opacity: 0.82,
  },
  entitlementButtonDisabled: {
    opacity: 0.62,
  },
  entitlementButtonText: {
    ...Type.button,
    ...textDirection,
    textAlign: 'center',
    color: '#FFFFFF',
  },
  upgradeCard: {
    marginTop: 20,
    paddingVertical: 18,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  upgradeRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  upgradeLabel: {
    flexShrink: 1,
    minWidth: 0,
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.semiBold,
    fontSize: 14,
  },
  upgradeValue: {
    ...textDirection,
    color: Palette.text,
    fontFamily: Fonts.bold,
    fontSize: 14,
  },
  upgradeDivider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: 'rgba(255,255,255,.09)',
    marginVertical: 11,
  },
  upgradeHint: {
    flexShrink: 1,
    ...textDirection,
    color: Palette.textMuted,
    fontFamily: Fonts.regular,
    fontSize: 12,
  },
  upgradeHintValue: {
    ...textDirection,
    color: 'rgba(255,255,255,.82)',
    fontFamily: Fonts.semiBold,
    fontSize: 12,
  },
  upgradeDeficit: {
    ...textDirection,
    color: '#FFB1B1',
    fontFamily: Fonts.medium,
    fontSize: 12,
    marginTop: 10,
  },
  upgradeError: {
    ...textDirection,
    color: '#FFB1B1',
    fontFamily: Fonts.regular,
    fontSize: 12,
    lineHeight: 20,
    marginTop: 12,
  },
  composer: {
    flexShrink: 0,
    minHeight: 72,
    padding: 10,
    paddingBottom: Platform.OS === 'ios' ? 18 : 10,
    ...rtlRowStyle,
    alignItems: 'flex-end',
    gap: 8,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
    backgroundColor: Palette.canvas,
  },
  attachmentStrip: {
    flexGrow: 0,
    maxHeight: 76,
    paddingHorizontal: 10,
    paddingTop: 8,
    backgroundColor: Palette.canvas,
  },
  stopButton: {
    alignSelf: 'center',
    minHeight: 48,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 6,
    paddingHorizontal: 16,
    paddingVertical: 7,
    borderRadius: 14,
    backgroundColor: Palette.surfaceRaised,
  },
  stopButtonText: {color: '#FFFFFF', fontFamily: Fonts.medium, fontSize: 12},
  attachmentChip: {
    minHeight: 48,
    maxWidth: 240,
    marginEnd: 8,
    paddingHorizontal: 8,
    borderRadius: 12,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 7,
    backgroundColor: Palette.surfaceRaised,
  },
  attachmentPreview: {width: 30, height: 30, borderRadius: 7},
  attachmentName: {
    flexShrink: 1,
    minWidth: 0,
    ...textDirection,
    maxWidth: 110,
    color: '#FFFFFF',
    fontFamily: Fonts.regular,
    fontSize: 12,
  },
  attachmentRemove: {color: '#FFFFFF', fontSize: 20, lineHeight: 22},
  attachmentRemoveButton: {
    width: 48,
    height: 48,
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  attachButton: {
    width: 48,
    height: 48,
    borderRadius: 15,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.surfaceRaised,
  },
  attachButtonText: {color: '#FFFFFF', fontSize: 24, lineHeight: 26},
  input: {
    ...textDirection,
    flex: 1,
    minWidth: 0,
    minHeight: 48,
    maxHeight: 110,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 11,
    color: '#FFFFFF',
    backgroundColor: Palette.surfaceRaised,
    fontFamily: Fonts.regular,
    fontSize: 14,
    lineHeight: 21,
  },
  sendButton: {
    width: 48,
    height: 48,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.primary,
  },
  sendButtonDisabled: {
    opacity: 0.38,
  },
});
