import {StyleSheet} from 'react-native';
import {
  Accessibility,
  Palette,
  Radius,
  Spacing,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../../constants/designSystem';

export const savedLibraryStyles = StyleSheet.create({
  container: {paddingBottom: Spacing.xl},
  createFolderCard: {
    marginTop: Spacing.sm,
    padding: Spacing.md,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    backgroundColor: Palette.surface,
  },
  createFolderTitle: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginBottom: Spacing.sm,
  },
  createFolderRow: {...rtlRowStyle, alignItems: 'center', gap: Spacing.sm},
  folderInput: {
    ...Type.body,
    ...textDirection,
    flex: 1,
    minWidth: 0,
    minHeight: Accessibility.minTouchTarget,
    paddingHorizontal: Spacing.md,
    paddingVertical: 0,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    backgroundColor: Palette.surfaceRaised,
    color: Palette.text,
  },
  createButton: {
    minWidth: 82,
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: Spacing.md,
    borderRadius: Radius.md,
    backgroundColor: Palette.primary,
  },
  createButtonDisabled: {opacity: 0.45},
  createButtonText: {...Type.bodyStrong, color: '#FFFFFF'},
  inlineError: {
    ...Type.caption,
    ...textDirection,
    color: Palette.danger,
    marginTop: Spacing.sm,
  },
  folderChips: {
    ...rtlRowStyle,
    gap: Spacing.xs,
    paddingVertical: Spacing.md,
    paddingHorizontal: Spacing.xxs,
  },
  folderChip: {
    maxWidth: 230,
    minHeight: 40,
    justifyContent: 'center',
    paddingHorizontal: Spacing.md,
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    backgroundColor: Palette.surface,
  },
  folderChipActive: {
    borderColor: 'rgba(75,142,247,0.55)',
    backgroundColor: Palette.primarySoft,
  },
  folderChipText: {...Type.caption, ...textDirection, color: Palette.textMuted},
  folderChipTextActive: {color: '#A9C9FF'},
  deleteFolderButton: {
    alignSelf: 'flex-end',
    minHeight: Accessibility.minTouchTarget,
    justifyContent: 'center',
    paddingHorizontal: Spacing.xs,
  },
  deleteFolderText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.danger,
  },
  actionError: {
    ...Type.caption,
    ...textDirection,
    color: Palette.danger,
    marginBottom: Spacing.sm,
  },
  retryNotice: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: Spacing.sm,
    marginBottom: Spacing.sm,
    padding: Spacing.sm,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    backgroundColor: Palette.surface,
  },
  retryNoticeText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    flex: 1,
  },
  retryNoticeAction: {
    ...Type.caption,
    color: Palette.primary,
  },
  folder: {marginTop: Spacing.md},
  folderTitle: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    paddingHorizontal: Spacing.xs,
    marginBottom: Spacing.xs,
  },
  list: {
    backgroundColor: Palette.surface,
    borderRadius: Radius.lg,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    overflow: 'hidden',
    paddingHorizontal: Spacing.md,
  },
  row: {
    ...rtlRowStyle,
    alignItems: 'center',
    minHeight: 96,
    paddingVertical: Spacing.sm,
    backgroundColor: Palette.surface,
  },
  thumbWrap: {
    width: 94,
    aspectRatio: 1.5,
    borderRadius: Radius.md,
    overflow: 'hidden',
    backgroundColor: Palette.surfaceRaised,
  },
  thumb: {width: '100%', height: '100%', resizeMode: 'cover'},
  playMark: {
    position: 'absolute',
    inset: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.2)',
  },
  playText: {color: Palette.text, fontSize: 14},
  copy: {flex: 1, marginHorizontal: Spacing.md},
  title: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  course: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  duration: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textFaint,
    marginTop: 2,
  },
  removeButton: {
    width: Accessibility.minTouchTarget,
    height: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  removeText: {fontSize: 24, color: Palette.textMuted},
  swipeDelete: {
    width: 88,
    minHeight: 96,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.danger,
  },
  swipeDeleteText: {...Type.bodyStrong, color: '#FFFFFF'},
  divider: {
    height: StyleSheet.hairlineWidth,
    backgroundColor: Palette.lineSoft,
  },
  moreWrap: {alignItems: 'center', marginTop: Spacing.lg},
  moreError: {
    ...Type.caption,
    ...textDirection,
    color: Palette.danger,
    marginBottom: Spacing.sm,
  },
  moreButton: {
    minWidth: 180,
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: Radius.pill,
    borderWidth: 1,
    borderColor: Palette.primary,
    paddingHorizontal: Spacing.lg,
  },
  moreButtonDisabled: {opacity: 0.56},
  moreButtonText: {...Type.bodyStrong, color: Palette.primary},
  pressed: {opacity: 0.72},
});
