import {StyleSheet} from 'react-native';
import {
  Accessibility,
  fixedIconSlot,
  Palette,
  Radius,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../../constants/designSystem';
import {Fonts} from '../../../constants/styleConstants';

const styles = StyleSheet.create({
  screen: {flex: 1, backgroundColor: Palette.canvas},
  scroll: {flex: 1},
  scrollContent: {paddingBottom: 28},
  hero: {width: '100%'},
  heroFrame: {width: '100%', alignSelf: 'center'},
  heroNavigation: {
    ...rtlRowStyle,
    minHeight: 64,
    alignItems: 'center',
    gap: 8,
    paddingVertical: 6,
  },
  heroNavigationTitle: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    flex: 1,
  },
  heroArtwork: {
    width: '100%',
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: Palette.surface,
  },
  heroImage: {width: '100%', height: '100%', resizeMode: 'cover'},
  backButton: {
    ...fixedIconSlot,
    borderRadius: Radius.md,
  },
  heroContent: {
    position: 'absolute',
    start: 0,
    end: 0,
    bottom: 18,
    width: '100%',
    alignSelf: 'center',
  },
  heroTitle: {
    ...Type.title,
    ...textDirection,
    color: Palette.text,
    width: '100%',
    alignSelf: 'flex-start',
    maxWidth: 720,
  },
  instructorByline: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 8,
  },
  heroSubtitle: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    width: '100%',
    alignSelf: 'flex-start',
    maxWidth: 680,
    marginTop: 4,
  },
  socialProofRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexWrap: 'wrap',
    columnGap: 16,
    rowGap: 6,
    marginTop: 14,
  },
  ratingGroup: {
    ...rtlRowStyle,
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 6,
    maxWidth: '100%',
    minWidth: 0,
    flexShrink: 1,
  },
  ratingText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.text,
    fontFamily: Fonts.semiBold,
    flexShrink: 1,
  },
  socialProofText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    flexShrink: 1,
  },
  socialProofDot: {
    width: 3,
    height: 3,
    borderRadius: 2,
    backgroundColor: Palette.textFaint,
  },
  priceAndAction: {
    marginTop: 18,
    ...rtlRowStyle,
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  primaryButton: {
    minHeight: 56,
    width: '100%',
    minWidth: 0,
    paddingHorizontal: 18,
    paddingVertical: 13,
    borderRadius: 16,
    backgroundColor: Palette.primary,
    ...rtlRowStyle,
    gap: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  primaryButtonPressed: {
    backgroundColor: Palette.primaryPressed,
    transform: [{scale: 0.985}],
  },
  primaryButtonText: {
    ...Type.button,
    ...textDirection,
    color: '#FFFFFF',
    textAlign: 'center',
    flexShrink: 1,
  },
  actionBar: {
    backgroundColor: Palette.canvas,
    paddingTop: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  actionBarContent: {width: '100%', alignSelf: 'center'},
  previewButton: {
    ...rtlRowStyle,
    minHeight: Accessibility.minTouchTarget,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    backgroundColor: Palette.surface,
    alignSelf: 'flex-start',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
    marginTop: 18,
    maxWidth: '100%',
  },
  previewButtonText: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    flexShrink: 1,
  },
  previewIcon: {color: Palette.text, fontSize: 12},
  disabled: {opacity: 0.55},
  content: {width: '100%', alignSelf: 'center'},
  courseIntro: {
    paddingTop: 22,
    paddingBottom: 24,
  },
  ratingAction: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
    paddingVertical: 12,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  ratingActionTitle: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
  },
  ratingStars: {...rtlRowStyle, alignItems: 'center', gap: 0, flexWrap: 'wrap'},
  ratingStarButton: {
    width: Accessibility.minTouchTarget,
    height: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ratingStar: {fontSize: 26, color: Palette.textFaint},
  ratingStarSelected: {color: Palette.text},
  ratingDeleteButton: {
    minHeight: Accessibility.minTouchTarget,
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  ratingDeleteText: {...Type.caption, color: Palette.textMuted},
  tabs: {
    ...rtlRowStyle,
    gap: 20,
    width: '100%',
    alignSelf: 'flex-start',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.lineSoft,
    marginBottom: 24,
  },
  tab: {
    flex: 1,
    minHeight: Accessibility.minTouchTarget,
    minWidth: 0,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 12,
  },
  tabActive: {borderBottomColor: Palette.text},
  tabText: {
    ...Type.bodyStrong,
    ...textDirection,
    textAlign: 'center',
    color: Palette.textMuted,
  },
  tabTextActive: {color: Palette.text},
  aboutWrap: {paddingBottom: 16},
  aboutGrid: {gap: 28},
  aboutGridTablet: {...rtlRowStyle, alignItems: 'flex-start', gap: 32},
  aboutMain: {flexGrow: 1, flexShrink: 1, minWidth: 0},
  sectionEyebrow: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    fontFamily: Fonts.semiBold,
  },
  sectionTitle: {
    ...Type.section,
    ...textDirection,
    color: Palette.text,
    marginTop: 4,
    width: '100%',
    alignSelf: 'flex-start',
    maxWidth: 650,
  },
  bodyCopy: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 10,
    width: '100%',
    alignSelf: 'flex-start',
    maxWidth: 700,
  },
  outcomes: {marginTop: 20, gap: 10},
  outcomeRow: {...rtlRowStyle, alignItems: 'center', gap: 12},
  outcomeNumber: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: Palette.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outcomeNumberText: {
    ...Type.caption,
    color: '#8DB6FF',
    fontFamily: Fonts.bold,
  },
  outcomeText: {
    ...Type.bodyStrong,
    ...textDirection,
    color: '#D9DEE7',
    flex: 1,
  },
  instructorCard: {
    width: '100%',
    ...rtlRowStyle,
    alignItems: 'flex-start',
    gap: 14,
    paddingTop: 22,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  instructorCardTablet: {width: '36%', flexShrink: 0},
  instructorImage: {
    width: 56,
    height: 64,
    borderRadius: 16,
    resizeMode: 'cover',
  },
  instructorCopy: {flex: 1, minWidth: 0},
  instructorLabel: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
  },
  instructorName: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    marginTop: 2,
  },
  instructorBio: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 4,
  },
  lockedOutline: {paddingBottom: 16},
  modulePreview: {
    marginTop: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.lineSoft,
  },
  moduleHeader: {
    minHeight: 76,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 12,
    paddingVertical: 18,
  },
  moduleNumber: {
    fontFamily: Fonts.bold,
    fontSize: 18,
    color: Palette.textMuted,
    minWidth: 32,
    textAlign: 'center',
  },
  moduleCopy: {flex: 1, minWidth: 0},
  moduleTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  moduleMeta: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  outlineItems: {
    borderTopWidth: 1,
    borderTopColor: Palette.lineSoft,
    paddingVertical: 8,
    gap: 2,
  },
  outlineItem: {
    minHeight: 72,
    borderRadius: 12,
    paddingHorizontal: 11,
    paddingVertical: 14,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 10,
  },
  outlineItemPreview: {backgroundColor: Palette.surface},
  outlineItemCopy: {flex: 1, minWidth: 0},
  outlineItemTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  outlineItemMeta: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  itemStatus: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: Radius.pill,
    backgroundColor: Palette.surfacePressed,
    flexShrink: 1,
    maxWidth: '34%',
  },
  itemStatusOpen: {backgroundColor: Palette.surfacePressed},
  itemStatusText: {...Type.caption, ...textDirection, color: Palette.textMuted},
  itemStatusTextOpen: {color: Palette.text, fontFamily: Fonts.semiBold},
  lockedNote: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 14,
  },
  modalRoot: {flex: 1, justifyContent: 'flex-end'},
  modalBackdrop: {flex: 1, backgroundColor: Palette.overlay},
  sheet: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    maxHeight: '92%',
    backgroundColor: Palette.surface,
    borderTopStartRadius: 28,
    borderTopEndRadius: 28,
    paddingTop: 10,
  },
  sheetHandle: {
    width: 42,
    height: 4,
    borderRadius: 2,
    alignSelf: 'center',
    backgroundColor: Palette.line,
    marginBottom: 8,
  },
  sheetNavigation: {
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 12,
    paddingBottom: 12,
  },
  sheetContext: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    flex: 1,
    minWidth: 0,
  },
  sheetClose: {
    width: Accessibility.minTouchTarget,
    height: Accessibility.minTouchTarget,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 16,
    backgroundColor: Palette.surfacePressed,
  },
  sheetCloseText: {fontSize: 28, color: Palette.text},
  sheetFooter: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
    paddingTop: 4,
  },
  sheetContent: {paddingBottom: 12},
  sheetScroll: {flexShrink: 1},
  retentionSheet: {maxHeight: '72%'},
  retentionContent: {alignItems: 'stretch', paddingBottom: 4},
  retentionMark: {
    width: 58,
    height: 58,
    borderRadius: 20,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.coinSoft,
    borderWidth: 1,
    borderColor: 'rgba(216,166,60,0.24)',
    marginBottom: 12,
  },
  retentionMarkText: {
    color: '#F0CB78',
    fontFamily: Fonts.medium,
    fontSize: 29,
  },
  retentionSecondary: {
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
  },
  retentionSecondaryText: {...Type.bodyStrong, color: Palette.textMuted},
  sheetEyebrow: {...Type.caption, ...textDirection, color: Palette.textMuted},
  sheetTitle: {
    ...Type.title,
    ...textDirection,
    color: Palette.text,
    marginTop: 3,
  },
  sheetDescription: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 7,
  },
  planList: {gap: 14, marginTop: 24},
  planCard: {
    padding: 18,
    minHeight: Accessibility.minTouchTarget,
    borderRadius: 18,
    backgroundColor: Palette.canvasSoft,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  planCardSelected: {
    borderColor: Palette.textMuted,
    backgroundColor: Palette.canvasSoft,
  },
  planHeader: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 8,
  },
  planName: {
    ...Type.section,
    ...textDirection,
    color: Palette.text,
    flexGrow: 1,
    flexShrink: 1,
    minWidth: 0,
  },
  planSelectedLabel: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    flexShrink: 1,
  },
  planPrice: {marginTop: 12, maxWidth: '100%'},
  planPriceText: {...Type.title, color: Palette.text},
  planBenefits: {gap: 9, marginTop: 18},
  planBenefitRow: {...rtlRowStyle, alignItems: 'flex-start', gap: 9},
  planCheck: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: Palette.textMuted,
    marginTop: 8,
    flexShrink: 0,
  },
  planBenefitText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    flex: 1,
    minWidth: 0,
  },
  planChoose: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    minHeight: Accessibility.minTouchTarget,
    gap: 12,
    marginTop: 14,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
    paddingTop: 8,
  },
  planChooseText: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    flexShrink: 1,
  },
  selectedPlanSummary: {
    marginTop: 14,
    paddingVertical: 16,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.lineSoft,
  },
  selectedPlanName: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  selectedPlanDetail: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  topupSummary: {
    gap: 2,
    marginTop: 16,
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: Radius.md,
    backgroundColor: Palette.canvasSoft,
  },
  topupMetric: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    minHeight: 36,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingVertical: 5,
  },
  topupMetricLabel: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    minWidth: 0,
    flexShrink: 1,
  },
  topupMetricValue: {...Type.bodyStrong, color: Palette.text},
  topupBalanceNote: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 8,
  },
  shortfallRow: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    paddingTop: 10,
    paddingBottom: 4,
    marginTop: 4,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  shortfallLabel: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    minWidth: 0,
    flexShrink: 1,
  },
  shortfallValue: {...Type.section, color: Palette.text},
  packageList: {gap: 9, marginTop: 14},
  packageUnavailable: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    paddingVertical: 12,
  },
  codeBox: {
    marginTop: 18,
    paddingTop: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  codeTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  codeRow: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    alignItems: 'stretch',
    gap: 8,
    marginTop: 9,
  },
  codeInput: {
    ...Type.body,
    ...textDirection,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 160,
    minWidth: 0,
    minHeight: 52,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: Palette.text,
    backgroundColor: Palette.canvasSoft,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  codeButton: {
    minWidth: 82,
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: Palette.surfacePressed,
    paddingHorizontal: 14,
    paddingVertical: 12,
    flexShrink: 1,
  },
  codeButtonText: {...Type.button, color: Palette.text},
  reviewCode: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textFaint,
    marginTop: 6,
  },
  packageCard: {
    width: '100%',
    minWidth: 0,
    padding: 15,
    minHeight: Accessibility.minTouchTarget,
    borderRadius: 18,
    backgroundColor: Palette.canvasSoft,
    borderWidth: 1,
    borderColor: 'transparent',
  },
  packageCardSufficient: {
    borderColor: Palette.primary,
    backgroundColor: Palette.primarySoft,
  },
  packageHeading: {alignItems: 'stretch', gap: 3},
  packageLabel: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
  },
  packageBadge: {
    ...Type.caption,
    ...textDirection,
    color: Palette.text,
    alignSelf: 'flex-start',
    maxWidth: '100%',
    fontFamily: Fonts.semiBold,
  },
  packageAmountRow: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    columnGap: 12,
    rowGap: 8,
    marginTop: 8,
  },
  packageCoins: {maxWidth: '100%'},
  packageCoinsText: {...Type.title, color: Palette.text},
  packageRemainder: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 6,
  },
  packagePrice: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    minWidth: 0,
    maxWidth: '100%',
    flexShrink: 1,
  },
  purchaseSummary: {
    marginTop: 16,
    marginBottom: 8,
  },
  summaryRow: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    paddingVertical: 14,
  },
  summaryRowTotal: {
    borderTopWidth: StyleSheet.hairlineWidth,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderColor: Palette.lineSoft,
  },
  summaryLabel: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    flexShrink: 1,
  },
  summaryCoins: {maxWidth: '100%'},
  summaryValue: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    marginTop: 2,
  },
  sheetPrimary: {
    minHeight: 56,
    borderRadius: 15,
    backgroundColor: Palette.action,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
    paddingHorizontal: 18,
    paddingVertical: 14,
  },
  sheetPrimaryText: {
    ...Type.button,
    ...textDirection,
    textAlign: 'center',
    color: Palette.text,
  },
  successMark: {
    width: 64,
    height: 64,
    borderRadius: 22,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(72,185,138,0.14)',
    marginBottom: 12,
  },
  successMarkText: {
    color: Palette.success,
    fontSize: 32,
    fontFamily: Fonts.bold,
  },
  centerText: {textAlign: 'center'},
  notice: {
    ...Type.caption,
    color: '#C7CED9',
    textAlign: 'center',
    marginTop: 12,
  },
  inlineNotice: {
    marginBottom: 14,
    padding: 12,
    borderRadius: 12,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  cachedDetailsNotice: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    minHeight: Accessibility.minTouchTarget,
    flexWrap: 'wrap',
    marginBottom: 14,
    padding: 12,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.lineSoft,
  },
  cachedDetailsText: {
    ...Type.caption,
    ...textDirection,
    color: '#C7CED9',
    flex: 1,
  },
  cachedDetailsAction: {
    ...Type.caption,
    color: Palette.text,
    fontFamily: Fonts.semiBold,
  },
  busyRow: {
    ...rtlRowStyle,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 9,
    marginTop: 12,
  },
  busyText: {...Type.caption, color: Palette.textMuted},
  pressed: {opacity: 0.75, transform: [{scale: 0.99}]},
});

export default styles;
