import {StyleSheet} from 'react-native';
import {
  Accessibility,
  Palette,
  Radius,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../../constants/designSystem';
import {Fonts} from '../../../constants/styleConstants';

const styles = StyleSheet.create({
  screen: {flex: 1, backgroundColor: Palette.canvas},
  hero: {width: '100%', minHeight: 350, overflow: 'hidden'},
  heroImage: {width: '100%', height: '100%', resizeMode: 'cover'},
  backButton: {
    position: 'absolute',
    start: 16,
    width: Accessibility.minTouchTarget,
    height: Accessibility.minTouchTarget,
    borderRadius: 22,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(7,10,16,0.72)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  backIcon: {color: Palette.text, fontSize: 36, lineHeight: 39, marginTop: -3},
  heroContent: {
    position: 'absolute',
    start: 0,
    end: 0,
    bottom: 18,
    width: '100%',
    alignSelf: 'center',
  },
  heroTitle: {
    ...Type.display,
    ...textDirection,
    color: Palette.text,
    marginTop: 9,
    width: '100%',
    alignSelf: 'flex-start',
    maxWidth: 720,
  },
  heroSubtitle: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    width: '100%',
    alignSelf: 'flex-start',
    maxWidth: 680,
    marginTop: 4,
  },
  socialProofRow: {
    ...rtlRowStyle,
    alignItems: 'center',
    alignSelf: 'flex-start',
    flexWrap: 'wrap',
    gap: 8,
    marginTop: 9,
  },
  ratingText: {...Type.caption, color: '#F0CB78', fontFamily: Fonts.semiBold},
  socialProofText: {...Type.caption, ...textDirection, color: '#D3D8E2'},
  socialProofDot: {
    width: 3,
    height: 3,
    borderRadius: 2,
    backgroundColor: Palette.textFaint,
  },
  priceAndAction: {
    marginTop: 18,
    ...rtlRowStyle,
    alignItems: 'center',
    flexWrap: 'wrap',
    gap: 10,
  },
  primaryButton: {
    minHeight: 56,
    minWidth: 190,
    paddingHorizontal: 24,
    borderRadius: 16,
    backgroundColor: Palette.primary,
    borderWidth: 1,
    borderColor: 'rgba(141,182,255,0.42)',
    alignItems: 'center',
    justifyContent: 'center',
    flexGrow: 1,
    maxWidth: 380,
    shadowColor: Palette.primary,
    shadowOffset: {width: 0, height: 8},
    shadowOpacity: 0.28,
    shadowRadius: 16,
    elevation: 6,
  },
  primaryButtonPressed: {
    backgroundColor: Palette.primaryPressed,
    transform: [{scale: 0.985}],
  },
  primaryButtonText: {...Type.button, color: '#FFFFFF', fontSize: 17},
  previewButton: {
    minHeight: 50,
    minWidth: 150,
    paddingHorizontal: 16,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.22)',
    backgroundColor: 'rgba(7,10,16,0.72)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  previewButtonText: {...Type.bodyStrong, color: Palette.text},
  disabled: {opacity: 0.55},
  content: {width: '100%', alignSelf: 'center'},
  courseIntro: {
    paddingTop: 18,
    paddingBottom: 22,
    marginBottom: 18,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.lineSoft,
  },
  ratingAction: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    flexWrap: 'wrap',
    gap: 10,
    marginBottom: 20,
    paddingHorizontal: 15,
    paddingVertical: 13,
    borderRadius: 16,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  ratingActionTitle: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
  },
  ratingStars: {...rtlRowStyle, alignItems: 'center', gap: 2},
  ratingStarButton: {
    width: Accessibility.minTouchTarget,
    height: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
  },
  ratingStar: {fontSize: 26, color: Palette.textFaint},
  ratingStarSelected: {color: '#F0CB78'},
  ratingDeleteButton: {
    minHeight: Accessibility.minTouchTarget,
    justifyContent: 'center',
    paddingHorizontal: 6,
  },
  ratingDeleteText: {...Type.caption, color: Palette.textMuted},
  tabs: {
    ...rtlRowStyle,
    gap: 6,
    padding: 4,
    width: '100%',
    maxWidth: 340,
    alignSelf: 'flex-start',
    borderRadius: 16,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    marginBottom: 26,
  },
  tab: {
    flex: 1,
    minHeight: Accessibility.minTouchTarget,
    minWidth: 0,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 15,
  },
  tabActive: {backgroundColor: Palette.surfacePressed},
  tabText: {...Type.bodyStrong, color: Palette.textFaint},
  tabTextActive: {color: Palette.text},
  aboutWrap: {paddingBottom: 50},
  aboutGrid: {gap: 22},
  aboutGridTablet: {...rtlRowStyle, alignItems: 'flex-start'},
  aboutMain: {flex: 1, minWidth: 0},
  sectionEyebrow: {
    ...Type.caption,
    ...textDirection,
    color: Palette.primary,
    fontFamily: Fonts.semiBold,
  },
  sectionTitle: {
    ...Type.section,
    ...textDirection,
    color: Palette.text,
    marginTop: 4,
    width: '100%',
    alignSelf: 'flex-start',
    maxWidth: 650,
  },
  bodyCopy: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 10,
    width: '100%',
    alignSelf: 'flex-start',
    maxWidth: 700,
  },
  outcomes: {marginTop: 20, gap: 10},
  outcomeRow: {...rtlRowStyle, alignItems: 'center', gap: 12},
  outcomeNumber: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: Palette.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  outcomeNumberText: {
    ...Type.caption,
    color: '#8DB6FF',
    fontFamily: Fonts.bold,
  },
  outcomeText: {
    ...Type.bodyStrong,
    ...textDirection,
    color: '#D9DEE7',
    flex: 1,
  },
  instructorCard: {
    width: '100%',
    maxWidth: 365,
    alignSelf: 'center',
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 14,
    padding: 14,
    borderRadius: 20,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  instructorImage: {
    width: 92,
    height: 112,
    borderRadius: 15,
    resizeMode: 'cover',
  },
  instructorCopy: {flex: 1},
  instructorLabel: {...Type.caption, ...textDirection, color: Palette.primary},
  instructorName: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    marginTop: 2,
  },
  instructorBio: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 4,
  },
  lockedOutline: {paddingBottom: 50},
  modulePreview: {
    marginTop: 10,
    borderRadius: 17,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    overflow: 'hidden',
  },
  moduleHeader: {
    minHeight: 76,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 12,
    padding: 14,
  },
  moduleNumber: {fontFamily: Fonts.bold, fontSize: 18, color: Palette.primary},
  moduleCopy: {flex: 1},
  moduleTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  moduleMeta: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  expandSymbol: {
    color: Palette.textMuted,
    fontSize: 23,
    transform: [{rotate: '0deg'}],
  },
  expandSymbolOpen: {transform: [{rotate: '180deg'}]},
  outlineItems: {
    borderTopWidth: 1,
    borderTopColor: Palette.lineSoft,
    padding: 8,
    gap: 4,
  },
  outlineItem: {
    minHeight: 60,
    borderRadius: 12,
    paddingHorizontal: 11,
    paddingVertical: 9,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 10,
  },
  outlineItemPreview: {backgroundColor: 'rgba(48,121,237,0.09)'},
  outlineItemCopy: {flex: 1, minWidth: 0},
  outlineItemTitle: {...Type.caption, ...textDirection, color: Palette.text},
  outlineItemMeta: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textFaint,
    marginTop: 2,
  },
  itemStatus: {
    paddingHorizontal: 9,
    paddingVertical: 5,
    borderRadius: Radius.pill,
    backgroundColor: Palette.surfacePressed,
  },
  itemStatusOpen: {backgroundColor: Palette.primarySoft},
  itemStatusText: {...Type.caption, color: Palette.textFaint},
  itemStatusTextOpen: {color: '#8DB6FF', fontFamily: Fonts.semiBold},
  lockedNote: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textFaint,
    marginTop: 14,
  },
  modalRoot: {flex: 1, justifyContent: 'flex-end'},
  modalBackdrop: {flex: 1, backgroundColor: Palette.overlay},
  sheet: {
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
    maxHeight: '88%',
    backgroundColor: Palette.surface,
    borderTopStartRadius: 28,
    borderTopEndRadius: 28,
    borderWidth: 1,
    borderColor: Palette.line,
    paddingTop: 10,
  },
  sheetHandle: {
    width: 42,
    height: 4,
    borderRadius: 2,
    alignSelf: 'center',
    backgroundColor: Palette.line,
    marginBottom: 18,
  },
  sheetContent: {paddingBottom: 4},
  sheetScroll: {flexShrink: 1},
  retentionSheet: {maxHeight: '72%'},
  retentionContent: {alignItems: 'stretch', paddingBottom: 4},
  retentionMark: {
    width: 58,
    height: 58,
    borderRadius: 20,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.coinSoft,
    borderWidth: 1,
    borderColor: 'rgba(216,166,60,0.24)',
    marginBottom: 12,
  },
  retentionMarkText: {
    color: '#F0CB78',
    fontFamily: Fonts.medium,
    fontSize: 29,
  },
  retentionSecondary: {
    minHeight: Accessibility.minTouchTarget,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 5,
  },
  retentionSecondaryText: {...Type.bodyStrong, color: Palette.textMuted},
  sheetEyebrow: {...Type.caption, ...textDirection, color: Palette.primary},
  sheetTitle: {
    ...Type.title,
    ...textDirection,
    color: Palette.text,
    marginTop: 3,
  },
  sheetDescription: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 7,
  },
  planList: {gap: 10, marginTop: 18},
  planCard: {
    padding: 15,
    borderRadius: 18,
    backgroundColor: Palette.canvasSoft,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  planCardSelected: {
    borderColor: 'rgba(52,120,246,0.55)',
    backgroundColor: 'rgba(52,120,246,0.08)',
  },
  planHeader: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 14,
  },
  planName: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    flex: 1,
  },
  planBenefits: {gap: 7, marginTop: 12},
  planBenefitRow: {...rtlRowStyle, alignItems: 'center', gap: 9},
  planCheck: {
    width: 7,
    height: 7,
    borderRadius: 4,
    backgroundColor: Palette.primary,
  },
  planBenefitText: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    flex: 1,
  },
  selectedPlanSummary: {
    marginTop: 14,
    padding: 13,
    borderRadius: 14,
    backgroundColor: Palette.primarySoft,
    borderWidth: 1,
    borderColor: 'rgba(52,120,246,0.28)',
  },
  selectedPlanName: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  selectedPlanDetail: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  topupSummary: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 16,
  },
  topupMetric: {
    flexGrow: 1,
    flexBasis: 120,
    minHeight: 64,
    justifyContent: 'center',
    paddingHorizontal: 13,
    borderRadius: 14,
    backgroundColor: Palette.canvasSoft,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  packageList: {gap: 9, marginTop: 18},
  packageUnavailable: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    paddingVertical: 18,
  },
  codeBox: {
    marginTop: 18,
    paddingTop: 16,
    borderTopWidth: StyleSheet.hairlineWidth,
    borderTopColor: Palette.lineSoft,
  },
  codeTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  codeRow: {...rtlRowStyle, alignItems: 'center', gap: 8, marginTop: 9},
  codeInput: {
    ...Type.body,
    ...textDirection,
    flex: 1,
    minHeight: 50,
    paddingHorizontal: 14,
    paddingVertical: 0,
    color: Palette.text,
    backgroundColor: Palette.canvasSoft,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  codeButton: {
    minWidth: 82,
    minHeight: 50,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: 14,
    backgroundColor: Palette.primary,
    paddingHorizontal: 14,
  },
  codeButtonText: {...Type.button, color: Palette.text},
  reviewCode: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textFaint,
    marginTop: 6,
  },
  packageCard: {
    width: '100%',
    minWidth: 0,
    padding: 15,
    borderRadius: 16,
    backgroundColor: Palette.canvasSoft,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  packageCardSufficient: {borderColor: 'rgba(52,120,246,0.46)'},
  packageHeading: {alignItems: 'stretch', gap: 3},
  packageLabel: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
  },
  packageBadge: {
    ...Type.caption,
    ...textDirection,
    color: Palette.primary,
    alignSelf: 'flex-start',
  },
  packageCoins: {marginTop: 5},
  packageCoinsText: {...Type.title, color: Palette.text},
  packageRemainder: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 6,
  },
  packagePrice: {
    ...Type.caption,
    ...textDirection,
    color: '#E9C66F',
    marginTop: 4,
  },
  purchaseSummary: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    gap: 16,
    justifyContent: 'space-between',
    marginVertical: 22,
    padding: 16,
    borderRadius: 17,
    backgroundColor: Palette.canvasSoft,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  summaryLabel: {...Type.caption, ...textDirection, color: Palette.textMuted},
  summaryValue: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    marginTop: 2,
  },
  sheetPrimary: {
    minHeight: 52,
    borderRadius: 15,
    backgroundColor: Palette.action,
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: 12,
  },
  sheetPrimaryText: {...Type.button, color: Palette.text},
  successMark: {
    width: 64,
    height: 64,
    borderRadius: 22,
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(72,185,138,0.14)',
    marginBottom: 12,
  },
  successMarkText: {
    color: Palette.success,
    fontSize: 32,
    fontFamily: Fonts.bold,
  },
  centerText: {textAlign: 'center'},
  notice: {
    ...Type.caption,
    color: '#C7CED9',
    textAlign: 'center',
    marginTop: 12,
  },
  inlineNotice: {
    marginBottom: 14,
    padding: 12,
    borderRadius: 12,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  cachedDetailsNotice: {
    ...rtlRowStyle,
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    marginBottom: 14,
    padding: 12,
    borderRadius: 12,
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  cachedDetailsText: {
    ...Type.caption,
    ...textDirection,
    color: '#C7CED9',
    flex: 1,
  },
  cachedDetailsAction: {
    ...Type.caption,
    color: Palette.primary,
    fontFamily: Fonts.semiBold,
  },
  busyRow: {
    ...rtlRowStyle,
    justifyContent: 'center',
    alignItems: 'center',
    gap: 9,
    marginTop: 12,
  },
  busyText: {...Type.caption, color: Palette.textMuted},
  pressed: {opacity: 0.75, transform: [{scale: 0.99}]},
});

export default styles;
