<?php

declare(strict_types=1);

namespace Tests\Feature;

use App\Http\Middleware\AppFrontNameSpace;
use App\Http\Middleware\WebsiteVisitorCount;
use App\Models\Order;
use App\Models\Package;
use App\Models\User;
use App\Services\KashierPaymentService;
use App\Services\KashierService;
use App\Services\StudentNotificationService;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Schema;
use Illuminate\Support\Facades\Storage;
use Tests\TestCase;

/**
 * Feature tests for the Kashier package payment integration.
 *
 * Covers:
 *  - Payment initiation (happy path, auth, duplicate prevention, missing package)
 *  - Callback handling (success, invalid signature, failed payment, idempotency)
 *  - Webhook handling (success, signature validation, idempotency)
 *  - Status polling
 *  - Business-logic assertions (coins credited, order updated, pivot record created)
 *
 * Uses SQLite :memory: (configured in phpunit.xml).
 * Creates schema inline to avoid dependency on the mixed migration history.
 */
class KashierPaymentTest extends TestCase
{
    // ─── Fixtures ────────────────────────────────────────────────────────────

    protected User    $user;
    protected Package $package;

    /** @var string Unique order reference used across scenarios */
    private string $orderRef;

    /** Price in EGP */
    private const PACKAGE_PRICE = 150.00;
    private const PACKAGE_COINS = 500;

    // Pre-computed HMAC for test params — generated by the same algorithm as KashierService
    private const TEST_MID      = 'MID-TEST-000';
    private const TEST_API_KEY  = 'test-api-key-not-a-secret';

    // ─── Schema / Data bootstrap ─────────────────────────────────────────────

    protected function setUp(): void
    {
        parent::setUp();
        $this->setUpSchema();
        $this->setUpData();

        // Disable tenant & visitor-count middleware that block all API requests
        // when there is no subdomain / TenantDomain record.
        $this->withoutMiddleware([AppFrontNameSpace::class, WebsiteVisitorCount::class]);
    }

    protected function tearDown(): void
    {
        $this->tearDownSchema();
        parent::tearDown();
    }

    private function setUpSchema(): void
    {
        Schema::create('settings', function (Blueprint $table) {
            $table->id();
            $table->string('site_name_ar')->nullable();
            $table->string('site_name_en')->nullable();
            $table->boolean('enforce_course_section_order')->default(false);
            $table->timestamps();
        });

        Schema::create('users', function (Blueprint $table) {
            $table->id();
            $table->string('name')->nullable();
            $table->string('name_ar')->nullable();
            $table->string('name_en')->nullable();
            $table->string('email')->unique()->nullable();
            $table->string('phone')->unique();
            $table->string('password')->nullable();
            $table->enum('role', ['admin', 'client', 'provider', 'merchant'])->default('client');
            $table->enum('gender', ['male', 'female', 'other'])->default('male');
            $table->date('birthday')->nullable();
            $table->integer('rate')->default(0);
            $table->float('balance')->default(0);
            $table->integer('wallet_coins')->default(0);
            $table->integer('wallet_purchased_coins')->default(0);
            $table->integer('wallet_reward_coins')->default(0);
            $table->string('api_token', 100)->unique()->nullable();
            $table->boolean('active')->default(true);
            $table->boolean('provider_request')->default(false);
            $table->rememberToken();
            $table->timestamps();
            $table->softDeletes();
        });

        Schema::create('packages', function (Blueprint $table) {
            $table->id();
            $table->string('name_ar')->nullable();
            $table->string('name_en')->nullable();
            $table->decimal('price', 10, 2)->default(0);
            $table->integer('coins')->default(0);
            $table->unsignedSmallInteger('sort_order')->default(100);
            $table->boolean('is_active')->default(true);
            $table->boolean('direct_enabled')->default(true);
            $table->timestamps();
        });

        // Package purchase pivot
        Schema::create('package_user', function (Blueprint $table) {
            $table->unsignedBigInteger('order_id')->nullable()->unique();
            $table->unsignedBigInteger('user_id');
            $table->unsignedBigInteger('package_id');
            $table->decimal('price', 10, 2)->nullable();
            $table->integer('coins')->nullable();
            $table->timestamps();
        });

        Schema::create('orders', function (Blueprint $table) {
            $table->id();
            $table->string('order_ref')->nullable()->unique();
            $table->string('transaction_id')->nullable()->unique();
            $table->unsignedBigInteger('user_id');
            $table->unsignedBigInteger('course_id')->nullable();
            $table->unsignedBigInteger('package_id')->nullable();
            $table->unsignedInteger('package_coins')->nullable();
            $table->string('checkout_request_key', 140)->nullable();
            $table->timestamp('checkout_expires_at')->nullable();
            $table->unsignedBigInteger('course_code_id')->nullable();
            $table->unsignedBigInteger('coupon_id')->nullable();
            $table->string('payment_method', 50)->default('online');
            $table->unsignedBigInteger('payment_method_id')->nullable();
            $table->string('payment_screenshot')->nullable();
            $table->json('payment_gateway_response')->nullable();
            $table->decimal('amount', 10, 2)->default(0);
            $table->decimal('discount_amount', 10, 2)->default(0);
            $table->decimal('final_amount', 10, 2)->default(0);
            $table->decimal('gateway_gross_amount', 10, 2)->nullable();
            $table->decimal('gateway_fee_amount', 10, 2)->nullable();
            $table->decimal('gateway_net_amount', 10, 2)->nullable();
            $table->string('gateway_currency', 3)->nullable();
            $table->string('gateway_settlement_status', 32)->nullable();
            $table->timestamp('gateway_settled_at')->nullable();
            $table->unsignedInteger('total_coins')->default(0);
            $table->unsignedInteger('paid_coins')->default(0);
            $table->unsignedInteger('reward_coins')->default(0);
            $table->string('status')->default('pending');
            $table->string('financial_status')->default('pending');
            $table->timestamp('reversed_at')->nullable();
            $table->text('reversal_reason')->nullable();
            $table->unsignedInteger('recovered_coins')->default(0);
            $table->unsignedInteger('unrecovered_coins')->default(0);
            $table->boolean('is_premium_user')->default(false);
            $table->text('notes')->nullable();
            $table->timestamp('approved_at')->nullable();
            $table->unsignedBigInteger('approved_by')->nullable();
            $table->timestamps();
            $table->softDeletes();
            $table->unique(['user_id', 'checkout_request_key']);
        });

        Schema::create('wallet_transactions', function (Blueprint $table) {
            $table->id();
            $table->uuid('public_id')->unique();
            $table->unsignedBigInteger('user_id');
            $table->string('delivery_key', 64)->nullable();
            $table->string('direction', 10);
            $table->string('category', 40);
            $table->string('bucket', 24)->default('legacy_reward');
            $table->unsignedInteger('amount');
            $table->unsignedInteger('paid_amount')->default(0);
            $table->unsignedInteger('reward_amount')->default(0);
            $table->integer('balance_after');
            $table->unsignedInteger('paid_balance_after')->default(0);
            $table->unsignedInteger('reward_balance_after')->default(0);
            $table->nullableMorphs('source');
            $table->string('idempotency_key', 140);
            $table->json('metadata')->nullable();
            $table->timestamp('occurred_at');
            $table->timestamps();
            $table->unique(['user_id', 'idempotency_key']);
        });

        Schema::create('order_financial_events', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('order_id');
            $table->unsignedBigInteger('actor_id')->nullable();
            $table->string('event_type', 32);
            $table->string('event_key', 96);
            $table->string('provider', 32)->nullable();
            $table->string('external_event_id', 191)->nullable();
            $table->unsignedInteger('recovered_coins')->default(0);
            $table->unsignedInteger('unrecovered_coins')->default(0);
            $table->text('reason')->nullable();
            $table->json('payload')->nullable();
            $table->timestamp('occurred_at');
            $table->timestamps();
            $table->unique(['order_id', 'event_key']);
            $table->unique(['provider', 'external_event_id']);
        });

        // Paid package acknowledgement is deliberately fail-closed unless
        // the immutable source/allocation schema exists. These lightweight
        // test tables mirror the production contract without unrelated FKs.
        Schema::create('wallet_credit_lots', function (Blueprint $table) {
            $table->id();
            $table->uuid('public_id')->unique();
            $table->unsignedBigInteger('user_id');
            $table->unsignedBigInteger('source_order_id')->nullable()->unique();
            $table->unsignedBigInteger('credit_transaction_id')->unique();
            $table->unsignedInteger('original_amount');
            $table->unsignedInteger('remaining_amount');
            $table->unsignedInteger('recovered_amount')->default(0);
            $table->string('status', 24)->default('active');
            $table->timestamp('credited_at');
            $table->timestamp('frozen_at')->nullable();
            $table->timestamp('resolved_at')->nullable();
            $table->json('metadata')->nullable();
            $table->timestamps();
        });

        // Paid mutations fail closed if the feature control-plane schema is
        // unavailable. An empty, readable table intentionally uses the live
        // checkout default for these integration scenarios.
        Schema::create('product_feature_flags', function (Blueprint $table) {
            $table->id();
            $table->string('key', 64)->unique();
            $table->boolean('enabled')->default(false);
            $table->unsignedTinyInteger('rollout_percentage')->default(100);
            $table->string('owner', 120);
            $table->string('reason', 255);
            $table->timestamp('expires_at')->nullable();
            $table->timestamps();
        });

        Schema::create('wallet_debit_allocations', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('wallet_transaction_id');
            $table->unsignedBigInteger('credit_lot_id');
            $table->unsignedBigInteger('course_order_id')->nullable();
            $table->unsignedInteger('amount');
            $table->string('entitlement_scope', 16)->default('course');
            $table->timestamp('allocated_at');
            $table->timestamps();
            $table->unique(['wallet_transaction_id', 'credit_lot_id']);
        });

        Schema::create('financial_entitlement_holds', function (Blueprint $table) {
            $table->id();
            $table->uuid('public_id')->unique();
            $table->unsignedBigInteger('user_id');
            $table->unsignedBigInteger('course_id');
            $table->unsignedBigInteger('course_order_id');
            $table->unsignedBigInteger('source_order_id');
            $table->unsignedBigInteger('enrollment_id')->nullable();
            $table->timestamp('enrollment_deactivated_at')->nullable();
            $table->unsignedBigInteger('certificate_id')->nullable();
            $table->timestamp('certificate_revoked_at')->nullable();
            $table->unsignedBigInteger('resolved_by')->nullable();
            $table->string('status', 24)->default('active');
            $table->string('entitlement_scope', 16)->default('course');
            $table->string('reason', 255)->nullable();
            $table->string('resolution', 24)->nullable();
            $table->text('resolution_note')->nullable();
            $table->timestamp('held_at');
            $table->timestamp('resolved_at')->nullable();
            $table->timestamps();
            $table->unique(['source_order_id', 'course_order_id']);
        });

        // Required by StudentNotificationService
        Schema::create('student_notifications', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('user_id');
            $table->string('delivery_key', 191)->nullable();
            $table->string('notification_type');
            $table->string('notifiable_type')->nullable();
            $table->unsignedBigInteger('notifiable_id')->nullable();
            $table->string('title_ar');
            $table->string('title_en');
            $table->text('message_ar');
            $table->text('message_en');
            $table->string('link')->nullable();
            $table->boolean('is_read')->default(false);
            $table->timestamp('read_at')->nullable();
            $table->timestamp('push_attempted_at')->nullable();
            $table->timestamp('push_sent_at')->nullable();
            $table->timestamps();
            $table->unique(['user_id', 'delivery_key']);
        });

        Schema::create('user_device_tokens', function (Blueprint $table) {
            $table->bigIncrements('id');
            $table->unsignedBigInteger('user_id');
            $table->string('device_token')->unique();
            $table->string('device_type')->nullable();
            $table->timestamps();
        });

        Schema::create('api_tokens', function (Blueprint $table) {
            $table->unsignedBigInteger('user_id')->index();
            $table->string('token', 80)->unique();
            $table->dateTime('issued_at')->nullable();
            $table->dateTime('expired_at');
        });

        Schema::create('student_section_progress', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('user_id');
            $table->unsignedBigInteger('course_section_id');
            $table->boolean('is_completed')->default(false);
            $table->timestamps();
        });

        Schema::create('photos', function (Blueprint $table) {
            $table->id();
            $table->string('path');
            $table->morphs('photoable');
            $table->enum('type', ['featured', 'gallery', 'identity', 'family', 'licence', 'certification'])
                ->default('featured');
            $table->timestamps();
        });

        Schema::create('payment_reconciliation_findings', function (Blueprint $table) {
            $table->id();
            $table->string('provider', 32);
            $table->unsignedBigInteger('order_id')->nullable();
            $table->string('order_ref', 191);
            $table->char('fingerprint', 64)->unique();
            $table->string('kind', 64);
            $table->string('local_status', 32)->nullable();
            $table->string('local_financial_status', 32)->nullable();
            $table->string('provider_status', 32)->nullable();
            $table->string('provider_transaction_id', 191)->nullable();
            $table->string('state', 16)->default('open');
            $table->unsignedInteger('attempts')->default(1);
            $table->timestamp('first_seen_at');
            $table->timestamp('last_seen_at');
            $table->timestamp('resolved_at')->nullable();
            $table->unsignedBigInteger('resolved_by')->nullable();
            $table->text('resolution_note')->nullable();
            $table->json('evidence')->nullable();
            $table->timestamps();
        });
    }

    private function tearDownSchema(): void
    {
        Schema::dropIfExists('payment_reconciliation_findings');
        Schema::dropIfExists('product_feature_flags');
        Schema::dropIfExists('financial_entitlement_holds');
        Schema::dropIfExists('wallet_debit_allocations');
        Schema::dropIfExists('wallet_credit_lots');
        Schema::dropIfExists('student_notifications');
        Schema::dropIfExists('user_device_tokens');
        Schema::dropIfExists('student_section_progress');
        Schema::dropIfExists('api_tokens');
        Schema::dropIfExists('photos');
        Schema::dropIfExists('order_financial_events');
        Schema::dropIfExists('wallet_transactions');
        Schema::dropIfExists('orders');
        Schema::dropIfExists('package_user');
        Schema::dropIfExists('packages');
        Schema::dropIfExists('users');
        Schema::dropIfExists('settings');
    }

    private function setUpData(): void
    {
        \DB::table('settings')->insert([
            'site_name_ar'                 => 'Rokn Test',
            'site_name_en'                 => 'Rokn Test',
            'enforce_course_section_order' => false,
            'created_at'                   => now(),
            'updated_at'                   => now(),
        ]);

        $this->user = User::create([
            'name'         => 'Test Student',
            'name_ar'      => 'طالب تجريبي',
            'name_en'      => 'Test Student',
            'email'        => 'pay-student@rokn-test.com',
            'phone'        => '01099999001',
            'password'     => Hash::make('secret1234'),
            'role'         => 'client',
            'gender'       => 'male',
            'birthday'     => '2000-01-01',
            'active'       => true,
            'wallet_coins' => 0,
            'wallet_purchased_coins' => 0,
            'wallet_reward_coins' => 0,
        ]);

        $this->package = Package::create([
            'name_ar' => 'باقة 500 عملة',
            'name_en' => '500 Coins Package',
            'price'   => self::PACKAGE_PRICE,
            'coins'   => self::PACKAGE_COINS,
            'is_active' => true,
            'direct_enabled' => true,
        ]);

        $this->orderRef = 'PKG-' . strtoupper(uniqid('TEST'));
    }

    // ─── Helpers ─────────────────────────────────────────────────────────────

    /**
     * Build valid Kashier callback/webhook query params with a correct HMAC signature.
     * Mirrors the algorithm in KashierService::validateSignature().
     */
    private function buildKashierParams(string $orderRef, string $paymentStatus, string $transactionId = 'TXN-001'): array
    {
        $params = [
            'merchantOrderId' => $orderRef,
            'paymentStatus'   => $paymentStatus,
            'transactionId'   => $transactionId,
            'orderId'         => 'KSH-999',
            'currency'        => 'EGP',
            'amount'          => number_format(self::PACKAGE_PRICE, 2, '.', ''),
            'cardBrand'       => 'VISA',
        ];

        // Build query string the same way KashierService does (exclude 'signature' and 'mode')
        $queryString = '';
        foreach ($params as $key => $value) {
            $queryString .= "&{$key}={$value}";
        }
        $queryString = ltrim($queryString, '&');

        $params['signature'] = hash_hmac('sha256', $queryString, self::TEST_API_KEY, false);

        return $params;
    }

    /**
     * Create a pending kashier order in the DB (pre-condition for callback/webhook tests).
     */
    private function createPendingOrder(?string $orderRef = null): Order
    {
        return Order::create([
            'user_id'        => $this->user->id,
            'package_id'     => $this->package->id,
            'package_coins'  => self::PACKAGE_COINS,
            'order_ref'      => $orderRef ?? $this->orderRef,
            'payment_method' => Order::PAYMENT_METHOD_KASHIER,
            'amount'         => self::PACKAGE_PRICE,
            'discount_amount'=> 0,
            'final_amount'   => self::PACKAGE_PRICE,
            'status'         => Order::STATUS_PENDING,
            'is_premium_user' => false,
        ]);
    }

    /**
     * Silence StudentNotificationService so notification side-effects don't fail tests.
     */
    private function mockNotifications(): void
    {
        $this->mock(StudentNotificationService::class, function ($mock) {
            $mock->shouldReceive('notifyUser')->andReturn(null)->byDefault();
        });
        // Also mock the static call path
        \Illuminate\Support\Facades\Queue::fake();
    }

    // =========================================================================
    // 1. INITIATE PAYMENT
    // =========================================================================

   public function test_authenticated_user_can_initiate_payment_for_a_package(): void
    {
        $response = $this->actingAs($this->user, 'api')
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
            ]);

        $response->assertStatus(200)
            ->assertJsonPath('success', true)
            ->assertJsonPath('status', 200)
            ->assertJsonPath('data.order_ref', $response->json('order_ref'))
            ->assertJsonStructure([
                'status',
                'success',
                'data',
                'message',
                'payment_url',
                'order_ref',
                'amount',
                'package' => ['id', 'name_ar', 'name_en', 'coins'],
            ]);

        // order_ref must start with 'PKG-'
        $this->assertStringStartsWith('PKG-', $response->json('order_ref'));

        // payment_url must be a valid Kashier checkout URL
        $this->assertStringContainsString('checkout.kashier.io', $response->json('payment_url'));
        $this->assertStringContainsString('MID-', $response->json('payment_url'));

        // A pending order must exist in the DB
        $this->assertDatabaseHas('orders', [
            'user_id'        => $this->user->id,
            'package_id'     => $this->package->id,
            'payment_method' => 'kashier',
            'status'         => 'pending',
            'financial_status' => Order::FINANCIAL_PENDING,
        ]);
    }

   public function test_unauthenticated_user_cannot_initiate_payment(): void
    {
        $response = $this->postJson('/api/v1/payment/initiate', [
            'package_id' => $this->package->id,
        ]);

        $response->assertStatus(401);

        $this->assertDatabaseMissing('orders', [
            'package_id' => $this->package->id,
        ]);
    }

   public function test_initiate_fails_with_invalid_package_id(): void
    {
        $response = $this->actingAs($this->user, 'api')
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => 99999, // does not exist
            ]);

        $response->assertStatus(422); // validation error
    }

   public function test_initiate_fails_when_package_id_is_missing(): void
    {
        $response = $this->actingAs($this->user, 'api')
            ->postJson('/api/v1/payment/initiate', []);

        $response->assertStatus(422)
            ->assertJsonPath('status', 422)
            ->assertJsonPath('success', false)
            ->assertJsonPath('code', 'validation_error')
            ->assertJsonPath('data', null)
            ->assertJsonValidationErrors(['package_id']);
    }

    public function test_repeated_initiate_resumes_the_same_recent_pending_checkout(): void
    {
        // First initiation
        $first = $this->actingAs($this->user, 'api')
            ->postJson('/api/v1/payment/initiate', ['package_id' => $this->package->id]);
        $first->assertStatus(200);
        $firstRef = $first->json('order_ref');

        // Second initiation — same user, same package
        $second = $this->actingAs($this->user, 'api')
            ->postJson('/api/v1/payment/initiate', ['package_id' => $this->package->id]);
        $second->assertStatus(200);
        $secondRef = $second->json('order_ref');

        // A double-tap must resume the retryable checkout instead of creating two
        // payable orders for the same intent.
        $this->assertSame($firstRef, $secondRef);
        $this->assertDatabaseHas('orders', [
            'order_ref' => $secondRef,
            'status'    => Order::STATUS_PENDING,
        ]);
        $this->assertSame(1, Order::query()->where('user_id', $this->user->id)->count());
    }

    public function test_closing_an_uncreated_provider_checkout_releases_it_for_a_fresh_retry(): void
    {
        $abandoned = $this->createPendingOrder('PKG-ABANDON-NOT-FOUND');
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([], 404),
        ]);

        $this->actingAs($this->user, 'api')
            ->postJson("/api/v1/payment/abandon/{$abandoned->order_ref}")
            ->assertOk()
            ->assertJsonPath('status', Order::STATUS_CANCELLED)
            ->assertJsonPath('financial_status', Order::FINANCIAL_CANCELLED);

        $key = '96e07193-d6a9-4b62-9976-b652b4e4f8a7';
        $fresh = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', $key)
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
                'idempotency_key' => $key,
            ]);

        $fresh->assertOk();
        self::assertNotSame($abandoned->order_ref, $fresh->json('order_ref'));
        self::assertSame(2, Order::query()->where('user_id', $this->user->id)->count());
    }

    public function test_a_new_same_package_intent_replaces_an_active_reference_absent_at_provider(): void
    {
        $pending = $this->createPendingOrder('PKG-ACTIVE-NOT-FOUND');
        $pending->forceFill([
            'checkout_request_key' => 'server-original-checkout-key',
            'checkout_expires_at' => now()->addMinutes(20),
        ])->save();
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([], 404),
        ]);

        $key = '96e07193-d6a9-4b62-9976-b652b4e4f8a7';
        $response = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', $key)
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
                'idempotency_key' => $key,
            ]);

        $response->assertOk();
        self::assertSame(Order::STATUS_CANCELLED, $pending->fresh()->status);
        self::assertNotSame($pending->order_ref, $response->json('order_ref'));
        self::assertSame(2, Order::query()->where('user_id', $this->user->id)->count());
    }

    public function test_closing_an_unpaid_provider_checkout_never_treats_the_success_envelope_as_payment(): void
    {
        $order = $this->createPendingOrder('PKG-ABANDON-UNPAID');
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([
                'response' => [
                    'status' => 'SUCCESS',
                    'paymentStatus' => 'unpaid',
                    'merchantOrderId' => $order->order_ref,
                ],
            ]),
        ]);

        $this->actingAs($this->user, 'api')
            ->postJson("/api/v1/payment/abandon/{$order->order_ref}")
            ->assertOk()
            ->assertJsonPath('status', Order::STATUS_CANCELLED)
            ->assertJsonPath('financial_status', Order::FINANCIAL_CANCELLED)
            ->assertJsonPath('coins_added', 0);

        self::assertSame(0, (int) $this->user->fresh()->wallet_coins);
        self::assertSame(0, Order::query()->where('status', Order::STATUS_APPROVED)->count());
    }

    public function test_closing_checkout_during_provider_outage_keeps_one_recoverable_intent(): void
    {
        $order = $this->createPendingOrder('PKG-ABANDON-PROVIDER-DOWN');
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([], 503),
        ]);

        $this->actingAs($this->user, 'api')
            ->postJson("/api/v1/payment/abandon/{$order->order_ref}")
            ->assertOk()
            ->assertJsonPath('status', Order::STATUS_PENDING)
            ->assertJsonPath('financial_status', Order::FINANCIAL_PENDING);

        self::assertSame(Order::STATUS_PENDING, $order->fresh()->status);
        self::assertSame(1, Order::query()->where('user_id', $this->user->id)->count());
    }

    public function test_payment_evidence_uses_private_storage_and_a_short_lived_signed_route(): void
    {
        config([
            'payment_evidence.disk' => 'payment-evidence-test',
            'filesystems.disks.payment-evidence-test' => [
                'driver' => 'local',
                'root' => storage_path('framework/testing/payment-evidence'),
                'visibility' => 'private',
            ],
        ]);
        Storage::fake('payment-evidence-test');
        Storage::fake('public');
        $path = 'payment-evidence/legacy-receipt.png';
        $bytes = base64_decode('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=', true);
        Storage::disk('payment-evidence-test')->put($path, $bytes);
        $order = $this->createPendingOrder('PKG-PRIVATE-EVIDENCE');
        $order->forceFill(['payment_screenshot' => '/storage/'.$path])->save();

        $url = (string) $order->fresh()->payment_screenshot_url;
        self::assertStringContainsString('/payment-evidence/'.$order->id, $url);
        self::assertStringNotContainsString($path, $url);

        $this->get($url)
            ->assertOk()
            ->assertHeader('Cache-Control', 'max-age=0, no-store, private')
            ->assertHeader('X-Content-Type-Options', 'nosniff');

        $tampered = preg_replace('/signature=[^&]+/', 'signature=invalid', $url);
        $this->get((string) $tampered)->assertForbidden();

        // A legacy public object with the same key is never used as fallback.
        Storage::disk('payment-evidence-test')->delete($path);
        Storage::disk('public')->put($path, $bytes);
        $this->get($url)->assertNotFound();

        foreach ([
            '../payment-evidence/receipt.png',
            'payment-evidence/../receipt.png',
            'payment-evidence//receipt.png',
            'C:\\payment-evidence\\receipt.png',
            'receipts/receipt.png',
        ] as $unsafePath) {
            $order->forceFill(['payment_screenshot' => $unsafePath])->save();
            self::assertNull($order->fresh()->payment_screenshot_url);
        }

        $order->forceFill(['payment_screenshot' => 'https://public.example.test/receipt.png'])->save();
        self::assertNull($order->fresh()->payment_screenshot_url);
    }

    public function test_a_new_package_does_not_rewrite_an_unrelated_older_checkout(): void
    {
        $pending = $this->createPendingOrder('PKG-RESUME-AFTER-REINSTALL');
        $pending->forceFill([
            'checkout_request_key' => 'server-original-checkout-key',
            'checkout_expires_at' => now()->addMinutes(20),
        ])->save();
        $otherPackage = Package::create([
            'name_ar' => 'باقة أخرى',
            'name_en' => 'Another package',
            'price' => 250,
            'coins' => 900,
        ]);
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([], 404),
        ]);
        $response = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', '96e07193-d6a9-4b62-9976-b652b4e4f8a7')
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $otherPackage->id,
                'idempotency_key' => '96e07193-d6a9-4b62-9976-b652b4e4f8a7',
            ]);

        $response->assertOk()
            ->assertJsonPath('package.id', $otherPackage->id);
        self::assertNotSame($pending->order_ref, $response->json('order_ref'));
        self::assertStringContainsString(
            'checkout.kashier.io',
            (string) $response->json('payment_url')
        );
        self::assertStringContainsString(
            rawurlencode((string) $response->json('order_ref')),
            (string) $response->json('payment_url')
        );
        self::assertSame(2, Order::query()->where('user_id', $this->user->id)->count());
        self::assertSame(
            1,
            Order::query()
                ->where('user_id', $this->user->id)
                ->where('package_id', $otherPackage->id)
                ->where('status', Order::STATUS_PENDING)
                ->count()
        );
        self::assertSame(Order::STATUS_CANCELLED, $pending->fresh()->status);
    }

    public function test_an_expired_provider_pending_checkout_does_not_monopolize_the_same_package(): void
    {
        $pending = $this->createPendingOrder('PKG-PROVIDER-STILL-PENDING');
        $pending->forceFill([
            'checkout_request_key' => 'server-original-checkout-key',
            'checkout_expires_at' => now()->subMinute(),
        ])->save();
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([
                'response' => [
                    'status' => 'PENDING',
                    'merchantOrderId' => $pending->order_ref,
                ],
            ], 200),
        ]);

        $response = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', '96e07193-d6a9-4b62-9976-b652b4e4f8a7')
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
                'idempotency_key' => '96e07193-d6a9-4b62-9976-b652b4e4f8a7',
            ]);

        $response->assertOk()
            ->assertJsonPath('package.id', $this->package->id);
        self::assertSame(Order::STATUS_CANCELLED, $pending->fresh()->status);
        self::assertNotSame($pending->order_ref, $response->json('order_ref'));
        self::assertSame(2, Order::query()->where('user_id', $this->user->id)->count());
    }

    public function test_an_expired_checkout_does_not_become_a_permanent_lock_during_provider_outage(): void
    {
        $pending = $this->createPendingOrder('PKG-EXPIRED-PROVIDER-DOWN');
        $pending->forceFill([
            'checkout_request_key' => 'server-original-checkout-key',
            'checkout_expires_at' => now()->subMinute(),
        ])->save();
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([], 503),
        ]);

        $key = '96e07193-d6a9-4b62-9976-b652b4e4f8a7';
        $response = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', $key)
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
                'idempotency_key' => $key,
            ]);

        $response->assertOk()
            ->assertJsonPath('package.id', $this->package->id);
        self::assertSame(Order::STATUS_CANCELLED, $pending->fresh()->status);
        self::assertNotSame($pending->order_ref, $response->json('order_ref'));
        self::assertSame(2, Order::query()->where('user_id', $this->user->id)->count());
    }

    public function test_an_expired_authorized_checkout_blocks_a_second_chargeable_attempt(): void
    {
        $pending = $this->createPendingOrder('PKG-PROVIDER-AUTHORIZED');
        $pending->forceFill([
            'checkout_request_key' => 'server-original-checkout-key',
            'checkout_expires_at' => now()->subMinute(),
        ])->save();
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([
                'response' => [
                    'status' => 'AUTHORIZED',
                    'merchantOrderId' => $pending->order_ref,
                ],
            ], 200),
        ]);

        $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', '96e07193-d6a9-4b62-9976-b652b4e4f8a7')
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
                'idempotency_key' => '96e07193-d6a9-4b62-9976-b652b4e4f8a7',
            ])
            ->assertStatus(409)
            ->assertJsonPath('code', 'pending_checkout_exists')
            ->assertJsonPath('order_ref', $pending->order_ref);

        self::assertSame(Order::STATUS_PENDING, $pending->fresh()->status);
        self::assertSame(1, Order::query()->where('user_id', $this->user->id)->count());
    }

    public function test_a_payment_under_review_returns_its_original_terms_without_a_payable_url(): void
    {
        $pending = $this->createPendingOrder('PKG-CAPTURE-AFTER-ACCOUNT-CLOSE');
        $pending->forceFill([
            'checkout_request_key' => 'server-original-checkout-key',
            'checkout_expires_at' => now()->addMinutes(20),
        ])->save();
        Http::fake(function () use ($pending) {
            // The learner may close the account after opening checkout while
            // Kashier still captures it. This capture is real but must be held
            // for review and must never expose another payable URL.
            $this->user->delete();

            return Http::response([
                'response' => [
                    'status' => 'CAPTURED',
                    'transactionId' => 'TXN-AFTER-ACCOUNT-CLOSE',
                    'merchantOrderId' => $pending->order_ref,
                    'amount' => self::PACKAGE_PRICE,
                    'currency' => 'EGP',
                ],
            ], 200);
        });

        $key = '96e07193-d6a9-4b62-9976-b652b4e4f8a7';
        $response = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', $key)
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
                'expected_amount' => self::PACKAGE_PRICE,
                'expected_coins' => self::PACKAGE_COINS,
                'idempotency_key' => $key,
            ]);

        $response->assertStatus(409)
            ->assertJsonPath('code', 'payment_under_review')
            ->assertJsonPath('order_ref', $pending->order_ref)
            ->assertJsonPath('checkout_state', 'payment_under_review')
            ->assertJsonPath('financial_status', Order::FINANCIAL_REVIEW_REQUIRED)
            ->assertJsonPath('amount', (int) self::PACKAGE_PRICE)
            ->assertJsonPath('package.id', $this->package->id)
            ->assertJsonPath('package.coins', self::PACKAGE_COINS);
        self::assertArrayNotHasKey('payment_url', (array) $response->json());
        $this->assertDatabaseHas('orders', [
            'id' => $pending->id,
            'status' => Order::STATUS_APPROVED,
            'financial_status' => Order::FINANCIAL_REVIEW_REQUIRED,
            'transaction_id' => 'TXN-AFTER-ACCOUNT-CLOSE',
            'checkout_request_key' => 'server-original-checkout-key',
            'final_amount' => self::PACKAGE_PRICE,
        ]);
        self::assertSame(1, Order::query()->where('user_id', $this->user->id)->count());
        self::assertSame(
            0,
            (int) User::withTrashed()->findOrFail($this->user->id)->wallet_coins
        );
    }

    public function test_provider_capture_with_wrong_amount_cannot_credit_or_release_a_second_checkout(): void
    {
        $pending = $this->createPendingOrder('PKG-CAPTURE-WRONG-AMOUNT');
        $pending->forceFill([
            'checkout_request_key' => 'server-original-checkout-key',
            'checkout_expires_at' => now()->addMinutes(20),
        ])->save();
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([
                'response' => [
                    'status' => 'CAPTURED',
                    'transactionId' => 'TXN-WRONG-AMOUNT',
                    'merchantOrderId' => $pending->order_ref,
                    'amount' => 1,
                    'currency' => 'EGP',
                ],
            ], 200),
        ]);

        $key = '96e07193-d6a9-4b62-9976-b652b4e4f8a7';
        $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', $key)
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
                'expected_amount' => self::PACKAGE_PRICE,
                'expected_coins' => self::PACKAGE_COINS,
                'idempotency_key' => $key,
            ])
            ->assertStatus(409)
            ->assertJsonPath('code', 'pending_checkout_exists')
            ->assertJsonPath('order_ref', $pending->order_ref);

        $this->assertDatabaseHas('orders', [
            'id' => $pending->id,
            'status' => Order::STATUS_PENDING,
            'financial_status' => Order::FINANCIAL_PENDING,
            'transaction_id' => null,
            'checkout_request_key' => 'server-original-checkout-key',
        ]);
        self::assertSame(1, Order::query()->where('user_id', $this->user->id)->count());
        self::assertSame(0, (int) $this->user->fresh()->wallet_coins);
    }

    public function test_expired_authorized_checkout_replay_keeps_the_original_attempt_open(): void
    {
        $key = 'server-original-checkout-key';
        $pending = $this->createPendingOrder('PKG-AUTHORIZED-REPLAY');
        $pending->forceFill([
            'checkout_request_key' => $key,
            'checkout_expires_at' => now()->subMinute(),
        ])->save();
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([
                'response' => [
                    'status' => 'AUTHORIZED',
                    'merchantOrderId' => $pending->order_ref,
                ],
            ], 200),
        ]);

        $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', $key)
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
                'idempotency_key' => $key,
            ])
            ->assertStatus(409)
            ->assertJsonPath('code', 'pending_checkout_exists')
            ->assertJsonPath('order_ref', $pending->order_ref);

        self::assertSame(Order::STATUS_PENDING, $pending->fresh()->status);
        self::assertSame(1, Order::query()->where('user_id', $this->user->id)->count());
    }

    public function test_an_expired_same_package_checkout_absent_at_provider_is_closed_before_retry(): void
    {
        $pending = $this->createPendingOrder('PKG-SAME-PACKAGE-ABANDONED');
        $pending->forceFill([
            'checkout_request_key' => 'server-original-checkout-key',
            'checkout_expires_at' => now()->subMinute(),
        ])->save();
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([], 404),
        ]);

        $response = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', '96e07193-d6a9-4b62-9976-b652b4e4f8a7')
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
                'idempotency_key' => '96e07193-d6a9-4b62-9976-b652b4e4f8a7',
            ]);

        $response->assertOk()
            ->assertJsonPath('package.id', $this->package->id);
        self::assertSame(Order::STATUS_CANCELLED, $pending->fresh()->status);
        self::assertNotSame($pending->order_ref, $response->json('order_ref'));
        self::assertSame(2, Order::query()->where('user_id', $this->user->id)->count());
    }

    public function test_a_legacy_checkout_without_a_stored_expiry_cannot_block_retries_forever(): void
    {
        $pending = $this->createPendingOrder('PKG-LEGACY-NO-EXPIRY');
        $pending->forceFill([
            'checkout_request_key' => 'server-legacy-checkout-key',
            'checkout_expires_at' => null,
            'created_at' => now()->subMinutes(Order::KASHIER_CHECKOUT_TTL_MINUTES + 1),
        ])->save();
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([], 404),
        ]);

        $key = '96e07193-d6a9-4b62-9976-b652b4e4f8a7';
        $response = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', $key)
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
                'idempotency_key' => $key,
            ]);

        $response->assertOk();
        self::assertSame(Order::STATUS_CANCELLED, $pending->fresh()->status);
        self::assertNotSame($pending->order_ref, $response->json('order_ref'));
    }

    public function test_an_expired_unpaid_provider_attempt_does_not_block_a_different_package(): void
    {
        $pending = $this->createPendingOrder('PKG-OTHER-PROVIDER-PENDING');
        $pending->forceFill([
            'checkout_request_key' => 'server-original-checkout-key',
            'checkout_expires_at' => now()->subMinute(),
        ])->save();
        $otherPackage = Package::create([
            'name_ar' => 'باقة أخرى',
            'name_en' => 'Another package',
            'price' => 250,
            'coins' => 900,
        ]);
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([
                'response' => [
                    'status' => 'PENDING',
                    'merchantOrderId' => $pending->order_ref,
                ],
            ], 200),
        ]);

        $response = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', '96e07193-d6a9-4b62-9976-b652b4e4f8a7')
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $otherPackage->id,
                'idempotency_key' => '96e07193-d6a9-4b62-9976-b652b4e4f8a7',
            ]);

        $response->assertOk()
            ->assertJsonPath('package.id', $otherPackage->id);
        self::assertSame(Order::STATUS_CANCELLED, $pending->fresh()->status);
        self::assertSame(2, Order::query()->where('user_id', $this->user->id)->count());
    }

    public function test_explicit_idempotency_key_replay_returns_the_same_checkout(): void
    {
        $key = '96e07193-d6a9-4b62-9976-b652b4e4f8a7';
        $payload = [
            'package_id' => $this->package->id,
            'idempotency_key' => $key,
        ];

        $first = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', $key)
            ->postJson('/api/v1/payment/initiate', $payload);
        $second = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', $key)
            ->postJson('/api/v1/payment/initiate', $payload);

        $first->assertOk()->assertJsonPath('idempotency_key', $key);
        $second->assertOk()->assertJsonPath('idempotency_key', $key);
        self::assertSame($first->json('order_ref'), $second->json('order_ref'));
        self::assertSame(1, Order::query()->where('user_id', $this->user->id)->count());
        $this->assertDatabaseHas('orders', [
            'user_id' => $this->user->id,
            'package_id' => $this->package->id,
            'checkout_request_key' => $key,
            'status' => Order::STATUS_PENDING,
        ]);
        self::assertNotNull(Order::query()->firstOrFail()->checkout_expires_at);
    }

    public function test_explicit_idempotency_replay_reports_a_completed_checkout_as_paid(): void
    {
        $key = '96e07193-d6a9-4b62-9976-b652b4e4f8a7';
        $payload = [
            'package_id' => $this->package->id,
            'idempotency_key' => $key,
        ];

        $first = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', $key)
            ->postJson('/api/v1/payment/initiate', $payload)
            ->assertOk();
        $order = Order::query()->where('order_ref', $first->json('order_ref'))->firstOrFail();
        app(KashierPaymentService::class)->fulfillOrder($order, 'TXN-IDEMPOTENT-PAID', [
            'merchantOrderId' => $order->order_ref,
            'paymentStatus' => 'SUCCESS',
            'transactionId' => 'TXN-IDEMPOTENT-PAID',
            'amount' => number_format((float) $order->final_amount, 2, '.', ''),
            'currency' => 'EGP',
        ]);

        $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', $key)
            ->postJson('/api/v1/payment/initiate', $payload)
            ->assertOk()
            ->assertJsonPath('success', true)
            ->assertJsonPath('checkout_state', 'paid')
            ->assertJsonPath('order_ref', $order->order_ref)
            ->assertJsonPath('transaction_id', 'TXN-IDEMPOTENT-PAID');

        self::assertSame(1, Order::query()->where('user_id', $this->user->id)->count());
        self::assertSame(self::PACKAGE_COINS, (int) $this->user->fresh()->wallet_coins);
    }

   public function test_idempotency_header_and_body_must_match_exactly(): void
    {
        $response = $this->actingAs($this->user, 'api')
            ->withHeader('Idempotency-Key', '96e07193-d6a9-4b62-9976-b652b4e4f8a7')
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
                'idempotency_key' => '1bc7f205-2870-456f-90f2-eed50143f46a',
            ]);

        $response->assertStatus(422)
            ->assertJsonPath('code', 'checkout_idempotency_mismatch');
        self::assertSame(0, Order::query()->count());
    }

   public function test_idempotency_key_cannot_be_reused_for_another_package(): void
    {
        $otherPackage = Package::create([
            'name_ar' => 'Other',
            'name_en' => 'Other',
            'price' => 250,
            'coins' => 900,
        ]);
        $key = '96e07193-d6a9-4b62-9976-b652b4e4f8a7';

        $this->actingAs($this->user, 'api')
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $this->package->id,
                'idempotency_key' => $key,
            ])
            ->assertOk();

        $this->actingAs($this->user, 'api')
            ->postJson('/api/v1/payment/initiate', [
                'package_id' => $otherPackage->id,
                'idempotency_key' => $key,
            ])
            ->assertStatus(409)
            ->assertJsonPath('code', 'checkout_idempotency_conflict');

        self::assertSame(1, Order::query()->where('user_id', $this->user->id)->count());
    }

    // =========================================================================
    // 2. CALLBACK (Kashier redirects WebView here)
    // =========================================================================

   public function test_successful_callback_approves_order_and_credits_coins(): void
    {
        $this->createPendingOrder();

        $params = $this->buildKashierParams($this->orderRef, 'SUCCESS', 'TXN-SUCCESS-001');

        $response = $this->getJson('/payment/callback?' . http_build_query($params));

        $response->assertStatus(200);
        // Should render the Blade result page — check it contains the success indicator
        $response->assertSee('success', false);

        // Order must be approved
        $this->assertDatabaseHas('orders', [
            'order_ref'      => $this->orderRef,
            'status'         => 'approved',
            'transaction_id' => 'TXN-SUCCESS-001',
        ]);

        // User wallet_coins must have been incremented
        $this->assertDatabaseHas('users', [
            'id'           => $this->user->id,
            'wallet_coins' => self::PACKAGE_COINS,
        ]);

        // Pivot record must exist
        $this->assertDatabaseHas('package_user', [
            'user_id'    => $this->user->id,
            'package_id' => $this->package->id,
            'coins'      => self::PACKAGE_COINS,
        ]);
    }

   public function test_callback_rejects_invalid_signature(): void
    {
        $this->createPendingOrder();

        $params = $this->buildKashierParams($this->orderRef, 'SUCCESS');
        // Tamper with the signature
        $params['signature'] = 'bad-signature-that-will-fail';

        $response = $this->getJson('/payment/callback?' . http_build_query($params));

        // Still returns 200 (renders a failure page) but does NOT approve the order
        $response->assertStatus(200);
        $response->assertSee('تعذّر التحقق من عملية الدفع', false);

        $this->assertDatabaseHas('orders', [
            'order_ref' => $this->orderRef,
            'status'    => 'pending', // unchanged
        ]);

        // Coins must NOT have been credited
        $this->assertDatabaseHas('users', [
            'id'           => $this->user->id,
            'wallet_coins' => 0,
        ]);
    }

   public function test_failed_payment_callback_marks_order_as_failed(): void
    {
        $this->createPendingOrder();

        $params = $this->buildKashierParams($this->orderRef, 'FAILED');

        $response = $this->getJson('/payment/callback?' . http_build_query($params));

        $response->assertStatus(200)
            ->assertSee('فشلت عملية الدفع', false);

        $this->assertDatabaseHas('orders', [
            'order_ref' => $this->orderRef,
            'status'    => Order::STATUS_CANCELLED,
        ]);

        // Coins must NOT have been credited
        $this->assertDatabaseHas('users', [
            'id'           => $this->user->id,
            'wallet_coins' => 0,
        ]);
    }

   public function test_callback_is_idempotent_for_already_approved_order(): void
    {
        // Create and immediately approve the order
        $order = $this->createPendingOrder();
        $order->update([
            'status'         => 'approved',
            'transaction_id' => 'TXN-ALREADY-DONE',
            'approved_at'    => now(),
        ]);
        // Give the user the coins as if already fulfilled
        $this->user->forceFill([
            'wallet_coins' => self::PACKAGE_COINS,
            'wallet_purchased_coins' => self::PACKAGE_COINS,
        ])->save();

        $params = $this->buildKashierParams($this->orderRef, 'SUCCESS', 'TXN-ALREADY-DONE');

        $response = $this->getJson('/payment/callback?' . http_build_query($params));

        $response->assertStatus(200);

        // transaction_id must NOT have been overwritten by the second call
        $this->assertDatabaseHas('orders', [
            'order_ref'      => $this->orderRef,
            'transaction_id' => 'TXN-ALREADY-DONE',
        ]);

        // wallet_coins must NOT have been doubled
        $this->assertDatabaseHas('users', [
            'id'           => $this->user->id,
            'wallet_coins' => self::PACKAGE_COINS, // same as before
        ]);
    }

   public function test_callback_returns_error_when_order_not_found(): void
    {
        // No order created — unknown order_ref
        $params = $this->buildKashierParams('PKG-UNKNOWN-REF', 'SUCCESS');

        $response = $this->getJson('/payment/callback?' . http_build_query($params));

        $response->assertStatus(200)
            ->assertSee('عملية الدفع غير متاحة', false);
    }

    // =========================================================================
    // 3. WEBHOOK (server-to-server backup)
    // =========================================================================

   public function test_webhook_approves_order_and_credits_coins(): void
    {
        $this->createPendingOrder();

        $params = $this->buildKashierParams($this->orderRef, 'SUCCESS', 'TXN-WEBHOOK-001');

        $response = $this->postJson('/payment/webhook', $params);

        $response->assertStatus(200)
            ->assertJsonPath('status', 200)
            ->assertJsonPath('success', true)
            ->assertJsonPath('data', null)
            ->assertJsonPath('message', 'Webhook processed successfully');

        $this->assertDatabaseHas('orders', [
            'order_ref'      => $this->orderRef,
            'status'         => 'approved',
            'transaction_id' => 'TXN-WEBHOOK-001',
        ]);

        $this->assertDatabaseHas('users', [
            'id'           => $this->user->id,
            'wallet_coins' => self::PACKAGE_COINS,
        ]);

        $this->assertDatabaseHas('package_user', [
            'user_id'    => $this->user->id,
            'package_id' => $this->package->id,
        ]);
    }

   public function test_webhook_approves_order_with_dashboard_event_payload(): void
    {
        $this->createPendingOrder('PKG-TEST-WEBHOOK');

        $payload = [
            'event' => 'pay',
            'data'  => [
                'merchantOrderId'         => 'PKG-TEST-WEBHOOK',
                'kashierOrderId'          => 'abc-123',
                'orderReference'          => 'TEST-ORD-1',
                'transactionId'           => 'TX-TEST-1',
                'status'                  => 'SUCCESS',
                'method'                  => 'card',
                'creationDate'            => '2026-07-03T00:28:46.641Z',
                'amount'                  => self::PACKAGE_PRICE,
                'currency'                => 'EGP',
                'transactionResponseCode' => '00',
                'channel'                 => 'online | e-commerce',
                'signatureKeys'           => [
                    'amount', 'channel', 'creationDate', 'currency', 'kashierOrderId',
                    'merchantOrderId', 'method', 'orderReference', 'status', 'transactionId',
                    'transactionResponseCode',
                ],
            ],
            'hash' => null,
        ];

        $signedPairs = [];
        foreach ($payload['data']['signatureKeys'] as $key) {
            $signedPairs[] = rawurlencode($key) . '=' . rawurlencode((string) $payload['data'][$key]);
        }
        $payload['hash'] = hash_hmac('sha256', implode('&', $signedPairs), self::TEST_API_KEY, false);

        $response = $this->postJson('/payment/webhook', $payload);

        $response->assertStatus(200)
            ->assertJsonPath('message', 'Webhook processed successfully');

        $this->assertDatabaseHas('orders', [
            'order_ref'      => 'PKG-TEST-WEBHOOK',
            'status'         => 'approved',
            'transaction_id' => 'TX-TEST-1',
        ]);
    }

   public function test_webhook_accepts_kashier_signature_inside_dashboard_event_data(): void
    {
        $this->createPendingOrder('PKG-TEST-WEBHOOK-SIGNATURE');

        $payload = [
            'event' => 'pay',
            'data'  => [
                'merchantOrderId'         => 'PKG-TEST-WEBHOOK-SIGNATURE',
                'kashierOrderId'          => 'abc-456',
                'orderReference'          => 'TEST-ORD-2',
                'transactionId'           => 'TX-TEST-2',
                'status'                  => 'SUCCESS',
                'method'                  => 'card',
                'creationDate'            => '2026-07-03T00:28:46.641Z',
                'amount'                  => self::PACKAGE_PRICE,
                'currency'                => 'EGP',
                'transactionResponseCode' => '00',
                'channel'                 => 'online | e-commerce',
                'signatureKeys'           => [
                    'amount', 'channel', 'creationDate', 'currency', 'kashierOrderId',
                    'merchantOrderId', 'method', 'orderReference', 'status', 'transactionId',
                    'transactionResponseCode',
                ],
            ],
        ];

        $signedPairs = [];
        foreach ($payload['data']['signatureKeys'] as $key) {
            $signedPairs[] = rawurlencode($key) . '=' . rawurlencode((string) $payload['data'][$key]);
        }
        $payload['data']['kashierSignature'] = hash_hmac(
            'sha256',
            implode('&', $signedPairs),
            self::TEST_API_KEY,
            false
        );

        $response = $this->postJson('/payment/webhook', $payload);

        $response->assertStatus(200)
            ->assertJsonPath('message', 'Webhook processed successfully');

        $this->assertDatabaseHas('orders', [
            'order_ref'      => 'PKG-TEST-WEBHOOK-SIGNATURE',
            'status'         => 'approved',
            'transaction_id' => 'TX-TEST-2',
        ]);
    }

   public function test_webhook_rejects_a_signature_when_a_declared_field_is_missing(): void
    {
        $this->createPendingOrder('PKG-TEST-WEBHOOK-MISSING-FIELD');

        $payload = [
            'event' => 'pay',
            'data' => [
                'merchantOrderId' => 'PKG-TEST-WEBHOOK-MISSING-FIELD',
                'transactionId' => 'TX-TEST-MISSING-FIELD',
                'status' => 'SUCCESS',
                'signatureKeys' => ['merchantOrderId', 'channel', 'status', 'transactionId'],
            ],
        ];
        $payload['data']['kashierSignature'] = hash_hmac(
            'sha256',
            'merchantOrderId=PKG-TEST-WEBHOOK-MISSING-FIELD&status=SUCCESS&transactionId=TX-TEST-MISSING-FIELD',
            self::TEST_API_KEY,
            false
        );

        $this->postJson('/payment/webhook', $payload)
            ->assertStatus(403)
            ->assertJsonPath('code', 'invalid_signature');

        $this->assertDatabaseHas('orders', [
            'order_ref' => 'PKG-TEST-WEBHOOK-MISSING-FIELD',
            'status' => 'pending',
        ]);
    }

   public function test_callback_server_error_keeps_order_pending_when_not_captured(): void
    {
        $this->createPendingOrder();

        $response = $this->get('/payment/callback?' . http_build_query([
            'paymentStatus'   => 'serverError',
            'merchantOrderId' => $this->orderRef,
            'currency'        => 'EGP',
            'amount'          => number_format(self::PACKAGE_PRICE, 2, '.', ''),
        ]));

        $response->assertStatus(200);
        $response->assertSee('نعالج عملية الدفع الآن', false);

        $this->assertDatabaseHas('orders', [
            'order_ref' => $this->orderRef,
            'status'    => 'pending',
        ]);
    }

   public function test_unsigned_failure_redirect_keeps_a_non_pending_order_unchanged(): void
    {
        $order = $this->createPendingOrder();
        $order->update(['status' => Order::STATUS_CANCELLED]);

        $response = $this->get('/payment/callback?' . http_build_query([
            'paymentStatus'   => 'FAILURE',
            'merchantOrderId' => $this->orderRef,
        ]));

        $response->assertStatus(200)
            ->assertSee('فشلت عملية الدفع', false);

        $this->assertDatabaseHas('orders', [
            'order_ref' => $this->orderRef,
            'status'    => Order::STATUS_CANCELLED,
        ]);
        self::assertSame(0, (int) $this->user->fresh()->wallet_coins);
    }

   public function test_unsigned_failure_redirect_for_a_missing_order_is_read_only(): void
    {
        $missingRef = 'PKG-MISSING-UNSIGNED';

        $response = $this->get('/payment/callback?' . http_build_query([
            'paymentStatus'   => 'FAILURE',
            'merchantOrderId' => $missingRef,
        ]));

        $response->assertStatus(200)
            ->assertSee('فشلت عملية الدفع', false)
            ->assertSee($missingRef, false);

        self::assertSame(0, Order::query()->count());
        self::assertSame(0, (int) $this->user->fresh()->wallet_coins);
    }

   public function test_webhook_rejects_invalid_signature(): void
    {
        $this->createPendingOrder();

        $params = $this->buildKashierParams($this->orderRef, 'SUCCESS');
        $params['signature'] = 'forged-signature';

        $response = $this->postJson('/payment/webhook', $params);

        $response->assertStatus(403)
            ->assertJsonPath('message', 'Invalid signature');

        $this->assertDatabaseHas('orders', [
            'order_ref' => $this->orderRef,
            'status'    => 'pending',
        ]);
    }

    public function test_signed_notification_without_a_payment_status_cannot_cancel_the_order(): void
    {
        $this->createPendingOrder('PKG-MISSING-PAYMENT-STATUS');
        $params = $this->buildKashierParams('PKG-MISSING-PAYMENT-STATUS', 'SUCCESS');
        unset($params['paymentStatus'], $params['signature']);
        $queryString = '';
        foreach ($params as $key => $value) {
            $queryString .= "&{$key}={$value}";
        }
        $params['signature'] = hash_hmac(
            'sha256',
            ltrim($queryString, '&'),
            self::TEST_API_KEY,
            false
        );

        $this->postJson('/payment/webhook', $params)
            ->assertStatus(202)
            ->assertJsonPath('message', 'Payment state accepted for reconciliation');

        $this->assertDatabaseHas('orders', [
            'order_ref' => 'PKG-MISSING-PAYMENT-STATUS',
            'status' => Order::STATUS_PENDING,
            'financial_status' => Order::FINANCIAL_PENDING,
        ]);
    }

    public function test_webhook_is_idempotent_for_already_approved_order(): void
    {
        $order = $this->createPendingOrder();
        app(KashierPaymentService::class)->fulfillOrder($order, 'TXN-FIRST', [
            'merchantOrderId' => $this->orderRef,
            'paymentStatus' => 'SUCCESS',
            'transactionId' => 'TXN-FIRST',
            'amount' => number_format(self::PACKAGE_PRICE, 2, '.', ''),
            'currency' => 'EGP',
        ]);

        $params = $this->buildKashierParams($this->orderRef, 'SUCCESS', 'TXN-FIRST');

        $response = $this->postJson('/payment/webhook', $params);

        $response->assertStatus(200)
            ->assertJsonPath('message', 'Already processed');

        // Coins must not have doubled
        $this->assertDatabaseHas('users', [
            'id'           => $this->user->id,
            'wallet_coins' => self::PACKAGE_COINS,
        ]);

        // transaction_id must NOT have changed
        $this->assertDatabaseHas('orders', [
            'order_ref'      => $this->orderRef,
            'transaction_id' => 'TXN-FIRST',
        ]);
    }

    public function test_settled_replay_without_transaction_id_keeps_the_original_settlement(): void
    {
        $order = $this->createPendingOrder('PKG-SETTLED-SPARSE-REPLAY');
        $payments = app(KashierPaymentService::class);
        $settled = $payments->fulfillOrder($order, 'TXN-ORIGINAL-SPARSE', [
            'merchantOrderId' => $order->order_ref,
            'paymentStatus' => 'SUCCESS',
            'transactionId' => 'TXN-ORIGINAL-SPARSE',
            'amount' => number_format(self::PACKAGE_PRICE, 2, '.', ''),
            'currency' => 'EGP',
        ]);

        $replayed = $payments->fulfillOrder($settled, null, [
            'merchantOrderId' => $order->order_ref,
            'paymentStatus' => 'SUCCESS',
            'amount' => number_format(self::PACKAGE_PRICE, 2, '.', ''),
            'currency' => 'EGP',
        ]);

        self::assertTrue($replayed->isFinanciallyEffective());
        self::assertSame('TXN-ORIGINAL-SPARSE', $replayed->transaction_id);
        self::assertSame(self::PACKAGE_COINS, (int) $this->user->fresh()->wallet_coins);
        self::assertSame(1, \DB::table('wallet_transactions')->where('category', 'package_purchase')->count());
    }

    public function test_provider_credentials_and_card_tokens_are_not_stored_with_the_order(): void
    {
        $order = $this->createPendingOrder('PKG-SANITIZED-EVIDENCE');

        $settled = app(KashierPaymentService::class)->fulfillOrder(
            $order,
            'TX-SANITIZED-EVIDENCE',
            [
                'merchantOrderId' => 'PKG-SANITIZED-EVIDENCE',
                'amount' => (float) $order->final_amount,
                'currency' => 'EGP',
                'requestCredentials' => [
                    'credentials' => [
                        'apiPassword' => 'provider-password',
                        'secretKey' => 'provider-secret',
                    ],
                ],
                'sourceOfFunds' => [
                    'cardInfo' => [
                        'ccvToken' => 'ccv-token-value',
                        'cardDataToken' => 'card-data-token-value',
                    ],
                ],
            ]
        );

        $stored = json_encode($settled->payment_gateway_response, JSON_THROW_ON_ERROR);
        self::assertStringNotContainsString('provider-password', $stored);
        self::assertStringNotContainsString('provider-secret', $stored);
        self::assertStringNotContainsString('ccv-token-value', $stored);
        self::assertStringNotContainsString('card-data-token-value', $stored);
        self::assertStringContainsString('[redacted]', $stored);
    }

   public function test_callback_and_webhook_replay_credit_the_wallet_exactly_once(): void
    {
        $this->createPendingOrder();
        $params = $this->buildKashierParams(
            $this->orderRef,
            'SUCCESS',
            'TXN-CALLBACK-WEBHOOK-RACE'
        );

        $this->getJson('/payment/callback?' . http_build_query($params))->assertOk();
        $this->postJson('/payment/webhook', $params)
            ->assertOk()
            ->assertJsonPath('message', 'Already processed');

        self::assertSame(self::PACKAGE_COINS, (int) $this->user->fresh()->wallet_coins);
        self::assertSame(1, \DB::table('wallet_transactions')->count());
        self::assertSame(1, \DB::table('wallet_credit_lots')->count());
        self::assertSame(1, \DB::table('package_user')->count());
    }

   public function test_stale_fulfillment_replays_are_serialized_to_one_credit(): void
    {
        $order = $this->createPendingOrder();
        $staleCallbackCopy = Order::query()->findOrFail($order->id);
        $staleWebhookCopy = Order::query()->findOrFail($order->id);
        $payments = app(KashierPaymentService::class);
        $evidence = [
            'merchantOrderId' => $this->orderRef,
            'paymentStatus' => 'SUCCESS',
            'transactionId' => 'TXN-STALE-REPLAY',
            'amount' => number_format(self::PACKAGE_PRICE, 2, '.', ''),
            'currency' => 'EGP',
        ];

        $payments->fulfillOrder($staleCallbackCopy, 'TXN-STALE-REPLAY', $evidence);
        $payments->fulfillOrder($staleWebhookCopy, 'TXN-STALE-REPLAY', $evidence);

        self::assertSame(self::PACKAGE_COINS, (int) $this->user->fresh()->wallet_coins);
        self::assertSame(1, \DB::table('wallet_transactions')->count());
        self::assertSame(1, \DB::table('wallet_credit_lots')->count());
        self::assertSame(1, \DB::table('package_user')->count());
        $this->assertDatabaseHas('orders', [
            'id' => $order->id,
            'status' => Order::STATUS_APPROVED,
            'transaction_id' => 'TXN-STALE-REPLAY',
        ]);
    }

   public function test_replay_with_a_different_transaction_is_queued_for_review(): void
    {
        $this->createPendingOrder();
        $first = $this->buildKashierParams(
            $this->orderRef,
            'SUCCESS',
            'TXN-ORIGINAL-CAPTURE'
        );
        $conflict = $this->buildKashierParams(
            $this->orderRef,
            'SUCCESS',
            'TXN-DIFFERENT-CAPTURE'
        );

        $this->postJson('/payment/webhook', $first)->assertOk();
        $this->postJson('/payment/webhook', $conflict)
            ->assertOk()
            ->assertJsonPath('message', 'Conflicting payment event queued for review');

        $this->assertDatabaseHas('orders', [
            'order_ref' => $this->orderRef,
            'transaction_id' => 'TXN-ORIGINAL-CAPTURE',
            'financial_status' => Order::FINANCIAL_REVIEW_REQUIRED,
        ]);
        self::assertSame(self::PACKAGE_COINS, (int) $this->user->fresh()->wallet_coins);
        self::assertSame(1, \DB::table('wallet_transactions')->count());
        self::assertSame(1, \DB::table('wallet_credit_lots')->count());
        self::assertSame(1, \DB::table('package_user')->count());
    }

   public function test_late_success_for_cancelled_checkout_recovers_the_captured_payment_once(): void
    {
        $order = $this->createPendingOrder();
        $order->update([
            'status' => Order::STATUS_CANCELLED,
            'financial_status' => Order::FINANCIAL_CANCELLED,
        ]);

        $params = $this->buildKashierParams(
            $this->orderRef,
            'SUCCESS',
            'TXN-LATE-CANCELLED'
        );
        $this->postJson('/payment/webhook', $params)
            ->assertOk()
            ->assertJsonPath('message', 'Webhook processed successfully');

        $this->assertDatabaseHas('orders', [
            'id' => $order->id,
            'status' => Order::STATUS_APPROVED,
            'financial_status' => Order::FINANCIAL_SETTLED,
            'transaction_id' => 'TXN-LATE-CANCELLED',
        ]);
        self::assertSame(self::PACKAGE_COINS, (int) $this->user->fresh()->wallet_coins);
        self::assertSame(1, \DB::table('wallet_transactions')->count());
        self::assertSame(1, \DB::table('package_user')->count());
    }

   public function test_late_success_for_expired_checkout_recovers_the_captured_payment_once(): void
    {
        $order = $this->createPendingOrder();
        $order->forceFill(['checkout_expires_at' => now()->subMinute()])->save();

        $params = $this->buildKashierParams(
            $this->orderRef,
            'SUCCESS',
            'TXN-LATE-EXPIRED'
        );
        $this->postJson('/payment/webhook', $params)
            ->assertOk()
            ->assertJsonPath('message', 'Webhook processed successfully');

        $this->assertDatabaseHas('orders', [
            'id' => $order->id,
            'status' => Order::STATUS_APPROVED,
            'financial_status' => Order::FINANCIAL_SETTLED,
            'transaction_id' => 'TXN-LATE-EXPIRED',
        ]);
        self::assertSame(self::PACKAGE_COINS, (int) $this->user->fresh()->wallet_coins);
        self::assertSame(1, \DB::table('wallet_transactions')->count());
        self::assertSame(1, \DB::table('package_user')->count());
    }

    public function test_success_without_a_transaction_id_is_not_fulfilled(): void
    {
        $order = $this->createPendingOrder();
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([
                'response' => ['status' => 'CAPTURED'],
            ], 200),
        ]);
        $params = $this->buildKashierParams($this->orderRef, 'SUCCESS', '');

        $this->postJson('/payment/webhook', $params)
            ->assertOk()
            ->assertJsonPath('message', 'Payment capture queued for review');

        $this->assertDatabaseHas('orders', [
            'id' => $order->id,
            'status' => Order::STATUS_PENDING,
            'financial_status' => Order::FINANCIAL_REVIEW_REQUIRED,
            'transaction_id' => null,
        ]);
        self::assertSame(0, (int) $this->user->fresh()->wallet_coins);
        self::assertSame(0, \DB::table('wallet_transactions')->count());
    }

    public function test_reconciliation_can_finish_a_capture_after_transaction_identity_arrives(): void
    {
        $order = $this->createPendingOrder('PKG-RECOVER-IDENTITY');
        Http::fake([
            'https://test-api.kashier.io/*' => Http::sequence()
                ->push([
                    'response' => ['status' => 'CAPTURED'],
                ], 200)
                ->push([
                    'response' => [
                        'status' => 'CAPTURED',
                        'transactionId' => 'TXN-RECOVERED-LATER',
                        'merchantOrderId' => $order->order_ref,
                        'amount' => self::PACKAGE_PRICE,
                        'currency' => 'EGP',
                    ],
                ], 200),
        ]);
        $params = $this->buildKashierParams($order->order_ref, 'SUCCESS', '');

        $this->postJson('/payment/webhook', $params)
            ->assertOk()
            ->assertJsonPath('message', 'Payment capture queued for review');

        $this->actingAs($this->user, 'api')
            ->postJson("/api/v1/payment/reconcile/{$order->order_ref}")
            ->assertOk()
            ->assertJsonPath('data.status', Order::STATUS_APPROVED)
            ->assertJsonPath('data.financial_status', Order::FINANCIAL_SETTLED);

        self::assertSame(self::PACKAGE_COINS, (int) $this->user->fresh()->wallet_coins);
        self::assertSame(1, \DB::table('wallet_transactions')->count());
    }

    public function test_a_signed_failure_cannot_quarantine_an_already_settled_capture(): void
    {
        $order = $this->createPendingOrder('PKG-SETTLED-THEN-FAILURE');
        $success = $this->buildKashierParams($order->order_ref, 'SUCCESS', 'TXN-SETTLED');
        $this->postJson('/payment/webhook', $success)->assertOk();

        $failure = $this->buildKashierParams($order->order_ref, 'FAILURE', 'TXN-FAILED-ATTEMPT');
        $this->postJson('/payment/webhook', $failure)
            ->assertOk()
            ->assertJsonPath('message', 'Already processed');

        $this->assertDatabaseHas('orders', [
            'id' => $order->id,
            'status' => Order::STATUS_APPROVED,
            'financial_status' => Order::FINANCIAL_SETTLED,
            'transaction_id' => 'TXN-SETTLED',
        ]);
        self::assertSame(self::PACKAGE_COINS, (int) $this->user->fresh()->wallet_coins);
    }

   public function test_order_api_verification_rejects_unsafe_references_before_http(): void
    {
        Http::fake();

        $result = app(KashierPaymentService::class)
            ->verifyOrderViaApi('PKG-../../provider-path');

        self::assertNull($result);
        Http::assertNothingSent();
    }

   public function test_missing_callback_transaction_id_can_be_recovered_from_kashier_api(): void
    {
        $order = $this->createPendingOrder();
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([
                'response' => [
                    'status' => 'CAPTURED',
                    'transactionId' => 'TXN-RECOVERED-BY-API',
                    'merchantOrderId' => $this->orderRef,
                    'amount' => self::PACKAGE_PRICE,
                    'currency' => 'EGP',
                ],
            ], 200),
        ]);
        $params = $this->buildKashierParams($this->orderRef, 'SUCCESS', '');

        $this->postJson('/payment/webhook', $params)
            ->assertOk()
            ->assertJsonPath('message', 'Webhook processed successfully');

        $this->assertDatabaseHas('orders', [
            'id' => $order->id,
            'status' => Order::STATUS_APPROVED,
            'financial_status' => Order::FINANCIAL_SETTLED,
            'transaction_id' => 'TXN-RECOVERED-BY-API',
        ]);
        self::assertSame(self::PACKAGE_COINS, (int) $this->user->fresh()->wallet_coins);
        self::assertSame(1, \DB::table('wallet_transactions')->count());
    }

   public function test_webhook_records_failure_for_failed_payment(): void
    {
        $this->createPendingOrder();

        $params = $this->buildKashierParams($this->orderRef, 'FAILED');

        $response = $this->postJson('/payment/webhook', $params);

        $response->assertStatus(200)
            ->assertJsonPath('message', 'Payment failure recorded');

        $this->assertDatabaseHas('orders', [
            'order_ref' => $this->orderRef,
            'status'    => Order::STATUS_CANCELLED,
        ]);
    }

    public function test_signed_failure_literal_closes_the_pending_attempt(): void
    {
        $this->createPendingOrder();

        $params = $this->buildKashierParams($this->orderRef, 'FAILURE');

        $this->postJson('/payment/webhook', $params)
            ->assertOk()
            ->assertJsonPath('message', 'Payment failure recorded');

        $this->assertDatabaseHas('orders', [
            'order_ref' => $this->orderRef,
            'status' => Order::STATUS_CANCELLED,
            'financial_status' => Order::FINANCIAL_CANCELLED,
        ]);
    }

   public function test_webhook_returns_404_for_unknown_order(): void
    {
        $params = $this->buildKashierParams('PKG-NONEXISTENT', 'SUCCESS');

        $response = $this->postJson('/payment/webhook', $params);

        $response->assertStatus(404)
            ->assertJsonPath('message', 'Order not found');
    }

    // =========================================================================
    // 4. STATUS POLLING
    // =========================================================================

   public function test_authenticated_user_can_poll_payment_status(): void
    {
        $order = $this->createPendingOrder();
        $order->update([
            'status'         => 'approved',
            'transaction_id' => 'TXN-POLL-001',
            'approved_at'    => now(),
        ]);

        $response = $this->actingAs($this->user, 'api')
            ->getJson("/api/v1/payment/status/{$this->orderRef}");

        $response->assertStatus(200)
            ->assertJsonPath('success', true)
            ->assertJsonPath('status', 'approved')
            ->assertJsonPath('status_code', 200)
            ->assertJsonPath('data.status', 'approved')
            ->assertJsonPath('transaction_id', 'TXN-POLL-001')
            ->assertJsonPath('order_ref', $this->orderRef)
            ->assertJsonStructure([
                'success',
                'order_ref',
                'status',
                'transaction_id',
                'amount',
                'package' => ['id', 'name_ar', 'name_en', 'coins'],
            ]);
    }

   public function test_status_poll_returns_pending_for_unprocessed_order(): void
    {
        $this->createPendingOrder();
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([
                'response' => ['status' => 'PENDING'],
            ], 200),
        ]);

        $response = $this->actingAs($this->user, 'api')
            ->getJson("/api/v1/payment/status/{$this->orderRef}");

        $response->assertStatus(200)
            ->assertJsonPath('success', true)
            ->assertJsonPath('status', 'pending');
    }

    public function test_explicit_reconciliation_keeps_an_active_checkout_absent_at_provider_open(): void
    {
        $order = $this->createPendingOrder('PKG-POLL-NOT-OPENED');
        $order->forceFill(['checkout_expires_at' => now()->addMinutes(20)])->save();
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([], 404),
        ]);

        $this->actingAs($this->user, 'api')
            ->postJson("/api/v1/payment/reconcile/{$order->order_ref}")
            ->assertOk()
            ->assertJsonPath('status', Order::STATUS_PENDING)
            ->assertJsonPath('financial_status', Order::FINANCIAL_PENDING);

        self::assertSame(Order::STATUS_PENDING, $order->fresh()->status);
        self::assertSame(0, (int) $this->user->fresh()->wallet_coins);
        self::assertSame(0, \Illuminate\Support\Facades\DB::table('wallet_transactions')->count());
    }

    public function test_explicit_reconciliation_closes_a_provider_reversed_attempt(): void
    {
        $order = $this->createPendingOrder('PKG-POLL-REVERSED');
        Http::fake([
            'https://test-api.kashier.io/*' => Http::response([
                'response' => [
                    'status' => 'REFUNDED',
                    'transactionId' => 'TXN-POLL-REVERSED',
                    'merchantOrderId' => $order->order_ref,
                    'amount' => self::PACKAGE_PRICE,
                    'currency' => 'EGP',
                ],
            ], 200),
        ]);

        $this->actingAs($this->user, 'api')
            ->postJson("/api/v1/payment/reconcile/{$order->order_ref}")
            ->assertOk()
            ->assertJsonPath('status', Order::STATUS_CANCELLED)
            ->assertJsonPath('financial_status', Order::FINANCIAL_REFUNDED);

        self::assertSame(0, (int) $this->user->fresh()->wallet_coins);
        self::assertSame(0, \Illuminate\Support\Facades\DB::table('wallet_transactions')->count());
    }

   public function test_unauthenticated_user_cannot_poll_status(): void
    {
        $this->createPendingOrder();

        $response = $this->getJson("/api/v1/payment/status/{$this->orderRef}");

        $response->assertStatus(401);
    }

   public function test_status_poll_returns_404_for_unknown_order_ref(): void
    {
        $response = $this->actingAs($this->user, 'api')
            ->getJson('/api/v1/payment/status/PKG-DOES-NOT-EXIST');

        $response->assertStatus(404)
            ->assertJsonPath('success', false);
    }

   public function test_user_cannot_poll_another_users_order(): void
    {
        // Create a second user and their order
        $otherUser = User::create([
            'name'     => 'Other User',
            'name_ar'  => 'مستخدم آخر',
            'name_en'  => 'Other User',
            'email'    => 'other@rokn-test.com',
            'phone'    => '01099999002',
            'password' => Hash::make('secret'),
            'role'     => 'client',
            'gender'   => 'male',
            'birthday' => '1995-01-01',
            'active'   => true,
        ]);

        // Create an order belonging to $otherUser
        $otherRef = 'PKG-OTHER-' . uniqid();
        Order::create([
            'user_id'        => $otherUser->id,
            'package_id'     => $this->package->id,
            'order_ref'      => $otherRef,
            'payment_method' => Order::PAYMENT_METHOD_KASHIER,
            'amount'         => self::PACKAGE_PRICE,
            'discount_amount'=> 0,
            'final_amount'   => self::PACKAGE_PRICE,
            'status'         => Order::STATUS_PENDING,
        ]);

        // $this->user tries to read otherUser's order
        $response = $this->actingAs($this->user, 'api')
            ->getJson("/api/v1/payment/status/{$otherRef}");

        $response->assertStatus(404); // must not be found for this user
    }

    // =========================================================================
    // 5. KASHIER SERVICE — UNIT-STYLE CHECKS
    // =========================================================================

   public function test_kashier_service_generates_hpp_url_with_correct_structure(): void
    {
        /** @var KashierService $kashier */
        $kashier = app(KashierService::class);

        $url = $kashier->getHppUrl(
            'ORD-TEST-1',
            '150.00',
            'EGP',
            'http://localhost/payment/callback'
        );

        $this->assertStringContainsString('checkout.kashier.io', $url);
        $this->assertStringContainsString('merchantId=', $url);
        $this->assertStringContainsString('orderId=ORD-TEST-1', $url);
        $this->assertStringContainsString('amount=150.00', $url);
        $this->assertStringContainsString('currency=EGP', $url);
        $this->assertStringContainsString('hash=', $url);
        $this->assertStringContainsString('merchantRedirect=', $url);
    }


   public function test_kashier_service_validates_correct_signature(): void
    {
        /** @var KashierService $kashier */
        $kashier = app(KashierService::class);

        $params = $this->buildKashierParams('ORD-SIG-TEST', 'SUCCESS', 'TXN-SIG-001');

        $this->assertTrue($kashier->validateSignature($params));
    }

   public function test_kashier_service_rejects_tampered_signature(): void
    {
        /** @var KashierService $kashier */
        $kashier = app(KashierService::class);

        $params = $this->buildKashierParams('ORD-SIG-TEST', 'SUCCESS', 'TXN-SIG-001');
        $params['signature'] = 'tampered-value';

        $this->assertFalse($kashier->validateSignature($params));
    }

   public function test_kashier_service_generates_order_hash_deterministically(): void
    {
        /** @var KashierService $kashier */
        $kashier = app(KashierService::class);

        $hash1 = $kashier->generateOrderHash('ORD-HASH-1', '100.00', 'EGP');
        $hash2 = $kashier->generateOrderHash('ORD-HASH-1', '100.00', 'EGP');

        // Same inputs must always produce the same hash
        $this->assertEquals($hash1, $hash2);
        $this->assertNotEmpty($hash1);
        $this->assertEquals(64, strlen($hash1)); // SHA-256 hex = 64 chars
    }

   public function test_order_model_scope_finds_by_order_ref(): void
    {
        $order = $this->createPendingOrder();

        $found = Order::byOrderRef($this->orderRef)->first();

        $this->assertNotNull($found);
        $this->assertEquals($order->id, $found->id);
    }

   public function test_is_premium_user_flag_is_false_for_new_user(): void
    {
        $this->assertFalse($this->user->isPremiumUser());

        $order = $this->createPendingOrder();
        $this->assertFalse($order->is_premium_user);
    }

   public function test_is_premium_user_flag_is_true_after_package_purchase(): void
    {
        // Simulate previous purchase
        $this->user->purchasedPackages()->attach($this->package->id, [
            'price' => self::PACKAGE_PRICE,
            'coins' => self::PACKAGE_COINS,
            'created_at' => now(),
        ]);

        $this->assertTrue($this->user->isPremiumUser());
    }
}
