import {StyleSheet} from 'react-native';
import {
  Palette,
  Radius,
  Spacing,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../../constants/designSystem';

export const galleryStyles = StyleSheet.create({
  container: {paddingBottom: Spacing.xl},
  loadNotice: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.sm,
  },
  grid: {
    direction: 'rtl',
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: Spacing.md,
  },
  projectCard: {
    borderRadius: Radius.lg,
    overflow: 'hidden',
    backgroundColor: Palette.surface,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  cover: {width: '100%', aspectRatio: 1.15, resizeMode: 'cover'},
  projectCopy: {padding: Spacing.md},
  projectTitle: {...Type.bodyStrong, ...textDirection, color: Palette.text},
  projectSummary: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.xs,
    minHeight: 40,
  },
  skillsRow: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    gap: Spacing.xs,
    marginTop: Spacing.sm,
  },
  overlay: {
    flex: 1,
    backgroundColor: Palette.overlay,
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  sheet: {
    width: '100%',
    maxWidth: 760,
    maxHeight: '90%',
    backgroundColor: Palette.canvasSoft,
    borderTopLeftRadius: Radius.xl,
    borderTopRightRadius: Radius.xl,
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: Palette.lineSoft,
  },
  detailCover: {width: '100%', aspectRatio: 1.5, resizeMode: 'cover'},
  detailLoader: {position: 'absolute', top: Spacing.lg, alignSelf: 'center'},
  mediaStrip: {
    direction: 'rtl',
    gap: Spacing.sm,
    paddingHorizontal: Spacing.xl,
    paddingVertical: Spacing.md,
  },
  mediaThumbGroup: {alignItems: 'center', gap: Spacing.xs},
  mediaThumb: {
    width: 76,
    height: 76,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Palette.lineSoft,
    overflow: 'hidden',
    backgroundColor: Palette.surface,
  },
  mediaThumbActive: {borderColor: Palette.primary, borderWidth: 2},
  mediaThumbImage: {width: '100%', height: '100%', resizeMode: 'cover'},
  mediaThumbPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  mediaThumbLabel: {...Type.caption, color: Palette.textMuted},
  mediaDelete: {paddingHorizontal: Spacing.sm, paddingVertical: Spacing.xs},
  mediaDeleteText: {...Type.caption, color: Palette.danger},
  detailCopy: {padding: Spacing.xl},
  detailTitle: {
    ...Type.title,
    ...textDirection,
    color: Palette.text,
    marginTop: Spacing.md,
  },
  detailSummary: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.sm,
  },
  fieldLabel: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: Spacing.md,
    marginBottom: Spacing.xs,
  },
  input: {
    ...Type.body,
    ...textDirection,
    minHeight: 52,
    color: Palette.text,
    backgroundColor: Palette.surface,
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Palette.line,
    paddingHorizontal: Spacing.md,
  },
  multiline: {minHeight: 112, textAlignVertical: 'top', paddingTop: Spacing.md},
  coverPicker: {
    minHeight: 120,
    marginTop: Spacing.md,
    borderRadius: Radius.md,
    borderStyle: 'dashed',
    borderWidth: 1,
    borderColor: Palette.textFaint,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  coverPickerLabel: {...Type.bodyStrong, color: Palette.textMuted},
  pickedMediaPreview: {width: '100%', position: 'relative'},
  pickedCover: {width: '100%', height: 160, resizeMode: 'cover'},
  pickedCoverFallback: {
    height: 160,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pickedMediaCount: {
    ...Type.caption,
    color: Palette.text,
    position: 'absolute',
    bottom: Spacing.sm,
    right: Spacing.sm,
    backgroundColor: Palette.overlay,
    borderRadius: Radius.pill,
    paddingHorizontal: Spacing.sm,
    paddingVertical: Spacing.xs,
  },
  eligibleSection: {marginTop: Spacing.sm},
  eligibleLoader: {alignSelf: 'flex-end', marginVertical: Spacing.md},
  eligibleList: {
    direction: 'rtl',
    flexDirection: 'row',
    gap: Spacing.sm,
    paddingVertical: Spacing.xs,
  },
  eligibleCard: {
    width: 220,
    minHeight: 88,
    ...rtlRowStyle,
    alignItems: 'center',
    overflow: 'hidden',
    borderRadius: Radius.md,
    borderWidth: 1,
    borderColor: Palette.line,
    backgroundColor: Palette.surface,
  },
  eligibleCardActive: {
    borderColor: Palette.primary,
    backgroundColor: Palette.primarySoft,
  },
  eligibleImage: {width: 72, alignSelf: 'stretch', resizeMode: 'cover'},
  eligibleCopy: {flex: 1, minWidth: 0, padding: Spacing.sm},
  eligibleCourse: {...Type.caption, ...textDirection, color: Palette.primary},
  eligibleTitle: {
    ...Type.bodyStrong,
    ...textDirection,
    color: Palette.text,
    marginTop: 2,
  },
  eligibleEmpty: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    paddingVertical: Spacing.sm,
  },
  manualEntryButton: {
    minHeight: 48,
    alignSelf: 'flex-end',
    justifyContent: 'center',
  },
  manualEntryLabel: {...Type.caption, color: Palette.primary},
  savingIndicator: {
    marginTop: Spacing.sm,
    alignItems: 'center',
    gap: Spacing.xs,
  },
  uploadProgressText: {...Type.caption, color: Palette.textMuted},
  draftError: {
    ...Type.caption,
    ...textDirection,
    color: Palette.danger,
    marginTop: Spacing.sm,
  },
  pressed: {opacity: 0.8, transform: [{scale: 0.99}]},
});
