import {StyleSheet} from 'react-native';
import {
  Palette,
  Type,
  rtlRowStyle,
  textDirection,
} from '../../../constants/designSystem';
import {Fonts} from '../../../constants/styleConstants';

export const feedSideBarStyles = StyleSheet.create({
  sheetBackground: {
    backgroundColor: Palette.canvas,
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
  },
  sheetIndicator: {
    backgroundColor: 'rgba(255,255,255,.28)',
    width: 42,
  },
  sheetContent: {
    paddingHorizontal: 16,
    paddingBottom: 42,
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
  },
  sheetHeader: {
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 14,
    paddingTop: 6,
  },
  sheetHeaderCopy: {
    flex: 1,
    minWidth: 0,
  },
  sheetEyebrow: {
    ...textDirection,
    color: Palette.textMuted,
    fontFamily: Fonts.semiBold,
    fontSize: 11,
  },
  sheetTitle: {
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.bold,
    fontSize: 20,
    lineHeight: 30,
  },
  progressPill: {
    minWidth: 58,
    minHeight: 38,
    paddingHorizontal: 10,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,.07)',
    paddingVertical: 8,
  },
  progressText: {
    color: '#FFFFFF',
    fontFamily: Fonts.semiBold,
    fontSize: 12,
    fontVariant: ['tabular-nums'],
  },
  progressTrack: {
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,.12)',
    overflow: 'hidden',
    marginTop: 14,
    marginBottom: 20,
  },
  progressFill: {
    height: '100%',
    backgroundColor: Palette.textMuted,
  },
  saveSheetContent: {
    paddingHorizontal: 18,
    paddingBottom: 38,
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
  },
  attachmentSheetContent: {
    paddingHorizontal: 18,
    paddingBottom: 38,
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
  },
  attachmentTitle: {
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.bold,
    fontSize: 22,
    lineHeight: 32,
    marginTop: 2,
  },
  attachmentBody: {
    ...Type.body,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 5,
    marginBottom: 16,
  },
  attachmentList: {gap: 8},
  attachmentRow: {
    minHeight: 64,
    paddingVertical: 14,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: Palette.lineSoft,
  },
  attachmentGlyph: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.surfaceRaised,
  },
  attachmentCopy: {flex: 1, minWidth: 0},
  attachmentName: {
    ...Type.bodyStrong,
    ...textDirection,
    color: '#FFFFFF',
  },
  attachmentMeta: {
    ...Type.caption,
    ...textDirection,
    color: Palette.textMuted,
    marginTop: 2,
  },
  attachmentAction: {
    ...textDirection,
    color: Palette.text,
    fontFamily: Fonts.semiBold,
    fontSize: 11,
    maxWidth: 90,
  },
  saveSheetTitle: {
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.bold,
    fontSize: 23,
    lineHeight: 34,
    marginTop: 2,
    marginBottom: 16,
  },
  folderLoader: {marginVertical: 24},
  folderList: {gap: 7},
  folderError: {
    ...textDirection,
    color: '#FF9A9A',
    fontFamily: Fonts.medium,
    fontSize: 12,
    lineHeight: 19,
    marginTop: 10,
  },
  folderRow: {
    minHeight: 52,
    borderRadius: 12,
    paddingHorizontal: 14,
    ...rtlRowStyle,
    alignItems: 'center',
    backgroundColor: Palette.surface,
    paddingVertical: 12,
    gap: 12,
  },
  folderRowText: {
    ...textDirection,
    flex: 1,
    minWidth: 0,
    color: '#FFFFFF',
    fontFamily: Fonts.medium,
    fontSize: 14,
  },
  folderRowAction: {
    ...textDirection,
    color: Palette.text,
    fontFamily: Fonts.semiBold,
    fontSize: 12,
    flexShrink: 1,
  },
  newFolderRow: {
    ...rtlRowStyle,
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: 8,
    marginTop: 14,
  },
  folderInput: {
    ...textDirection,
    flexGrow: 1,
    flexShrink: 1,
    flexBasis: 160,
    minWidth: 0,
    minHeight: 52,
    borderRadius: 14,
    paddingHorizontal: 14,
    color: '#FFFFFF',
    fontFamily: Fonts.regular,
    fontSize: 14,
    backgroundColor: Palette.surface,
    paddingVertical: 12,
  },
  createFolderButton: {
    minHeight: 52,
    minWidth: 110,
    paddingHorizontal: 14,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Palette.surfaceRaised,
    paddingVertical: 12,
  },
  createFolderButtonDisabled: {opacity: 0.45},
  createFolderButtonText: {
    ...textDirection,
    textAlign: 'center',
    color: '#FFFFFF',
    fontFamily: Fonts.semiBold,
    fontSize: 12,
  },
  removeSaveButton: {
    minHeight: 48,
    alignSelf: 'flex-end',
    paddingVertical: 13,
    paddingHorizontal: 4,
    marginTop: 5,
  },
  removeSaveText: {color: '#F28B91', fontFamily: Fonts.medium, fontSize: 12},
  pressed: {opacity: 0.75},
});
