import {StyleSheet} from 'react-native';
import {rtlRowStyle, textDirection} from '../../../constants/designSystem';
import {Fonts} from '../../../constants/styleConstants';

export const feedSideBarStyles = StyleSheet.create({
  sheetBackground: {
    backgroundColor: '#0B1017',
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
  },
  sheetIndicator: {
    backgroundColor: 'rgba(255,255,255,.28)',
    width: 42,
  },
  sheetContent: {
    paddingHorizontal: 16,
    paddingBottom: 42,
    width: '100%',
    maxWidth: 760,
    alignSelf: 'center',
  },
  sheetHeader: {
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 14,
    paddingTop: 6,
  },
  sheetHeaderCopy: {
    flex: 1,
  },
  sheetEyebrow: {
    ...textDirection,
    color: '#76A9FF',
    fontFamily: Fonts.semiBold,
    fontSize: 11,
  },
  sheetTitle: {
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.bold,
    fontSize: 20,
    lineHeight: 30,
  },
  progressPill: {
    minWidth: 58,
    height: 38,
    paddingHorizontal: 10,
    borderRadius: 19,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255,255,255,.07)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,.1)',
  },
  progressText: {
    color: '#FFFFFF',
    fontFamily: Fonts.semiBold,
    fontSize: 12,
    fontVariant: ['tabular-nums'],
  },
  progressTrack: {
    height: 3,
    borderRadius: 2,
    backgroundColor: 'rgba(255,255,255,.12)',
    overflow: 'hidden',
    marginTop: 14,
    marginBottom: 20,
  },
  progressFill: {
    height: '100%',
    backgroundColor: '#4B8EF7',
  },
  saveSheetContent: {
    paddingHorizontal: 18,
    paddingBottom: 38,
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
  },
  attachmentSheetContent: {
    paddingHorizontal: 18,
    paddingBottom: 38,
    width: '100%',
    maxWidth: 680,
    alignSelf: 'center',
  },
  attachmentTitle: {
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.bold,
    fontSize: 22,
    lineHeight: 32,
    marginTop: 2,
  },
  attachmentBody: {
    ...textDirection,
    color: 'rgba(255,255,255,.68)',
    fontFamily: Fonts.regular,
    fontSize: 13,
    lineHeight: 21,
    marginTop: 5,
    marginBottom: 16,
  },
  attachmentList: {gap: 8},
  attachmentRow: {
    minHeight: 64,
    borderRadius: 16,
    paddingHorizontal: 12,
    ...rtlRowStyle,
    alignItems: 'center',
    gap: 10,
    backgroundColor: '#121923',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,.08)',
  },
  attachmentGlyph: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(75,142,247,.18)',
  },
  attachmentCopy: {flex: 1},
  attachmentName: {
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.medium,
    fontSize: 13,
  },
  attachmentMeta: {
    ...textDirection,
    color: 'rgba(255,255,255,.46)',
    fontFamily: Fonts.regular,
    fontSize: 10,
    marginTop: 2,
  },
  attachmentAction: {
    color: '#76A9FF',
    fontFamily: Fonts.semiBold,
    fontSize: 11,
    maxWidth: 90,
  },
  saveSheetTitle: {
    ...textDirection,
    color: '#FFFFFF',
    fontFamily: Fonts.bold,
    fontSize: 23,
    lineHeight: 34,
    marginTop: 2,
    marginBottom: 16,
  },
  folderLoader: {marginVertical: 24},
  folderList: {gap: 7},
  folderError: {
    ...textDirection,
    color: '#FF9A9A',
    fontFamily: Fonts.medium,
    fontSize: 12,
    lineHeight: 19,
    marginTop: 10,
  },
  folderRow: {
    minHeight: 52,
    borderRadius: 14,
    paddingHorizontal: 14,
    ...rtlRowStyle,
    alignItems: 'center',
    backgroundColor: '#121923',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,.07)',
  },
  folderRowText: {
    ...textDirection,
    flex: 1,
    color: '#FFFFFF',
    fontFamily: Fonts.medium,
    fontSize: 14,
  },
  folderRowAction: {color: '#76A9FF', fontFamily: Fonts.semiBold, fontSize: 12},
  newFolderRow: {...rtlRowStyle, alignItems: 'center', gap: 8, marginTop: 14},
  folderInput: {
    ...textDirection,
    flex: 1,
    minHeight: 52,
    borderRadius: 14,
    paddingHorizontal: 14,
    color: '#FFFFFF',
    fontFamily: Fonts.regular,
    fontSize: 14,
    backgroundColor: '#121923',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,.1)',
  },
  createFolderButton: {
    minHeight: 52,
    minWidth: 110,
    paddingHorizontal: 14,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#236FE8',
  },
  createFolderButtonDisabled: {opacity: 0.45},
  createFolderButtonText: {
    color: '#FFFFFF',
    fontFamily: Fonts.semiBold,
    fontSize: 12,
  },
  removeSaveButton: {
    alignSelf: 'flex-end',
    paddingVertical: 13,
    paddingHorizontal: 4,
    marginTop: 5,
  },
  removeSaveText: {color: '#F28B91', fontFamily: Fonts.medium, fontSize: 12},
  pressed: {opacity: 0.75},
});
